<?php

namespace SwitcherCore\Modules\Juniper;

use SnmpWrapper\Oid;

class System extends \SwitcherCore\Modules\General\Switches\System {
    use InterfacesTrait;
    function getPrettyFiltered($filter = []) {
        $pretty =  parent::getPrettyFiltered($filter); // TODO: Change the autogenerated stub
        
        return $pretty;
    }

    public function getPretty() {
        $data = parent::getPretty();
        if(!$this->getResponseByName('jnx.sysUptimeSeconds')->error()) {
            $data['uptime_sec'] = $this->getResponseByName('jnx.sysUptimeSeconds')->fetchAll()[0]->getValue();
            $data['uptime'] = $this->getResponseByName('jnx.sysUptimeSeconds')->fetchAll()[0]->getValueAsTimeTicks();
        }
        return $data;
    }

    public function run($filter = []) {
        $oids = $this->oids->getOidsByRegex('^sys\..*');
        $oids = array_merge($oids, [$this->oids->getOidByName('jnx.sysUptimeSeconds')]);
        $oArray = [];
        foreach ($oids as $oid) {
            $oArray[] = Oid::init($oid->getOid(),true);
        }
        $this->response = $this->formatResponse($this->snmp->walk($oArray));
        return $this;
    }
}