  - {name: sfp.mediaVendorName, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.3}
  - {name: sfp.mediaPartNumber, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.4}
  - {name: sfp.mediaSerialNum, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.5}
  - {name: sfp.mediaFiberType, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.6, values: {1: single-mode, 2: multi-modeE50, 3: multi-mode50, 4: multi-mode625, 5: Cooper, 6: single-modeKm, 7: multi-modeOM3}} # raisecomOpticalTransceiverMediaType
  - {name: sfp.mediaConnectorType, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.2, values: {0: unknown, 1: unknown, 2: SC, 3: db9, 4: hssdc, 5: bnc-tnc, 6: Coaxial, 7: fiber-jack, 8: LC, 9: Cooper, 10: m, 11: SG, 12: fiber-pigtail, 13: mpo-parallel-optic, 21: hssdcII, 22: Cooper, 23: Cooper}}
  - {name: sfp.mediaBaudRate, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.14} #raisecomOpticalTransceiverBRMin. Value for sfp will be equal to raisecomOpticalTransceiverBRMax. Divide value by 1000 to get in Gbps
  - {name: sfp.mediaEthComplianceCodes, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.18}
  - {name: sfp.mediaWaveLength, oid: .1.3.6.1.4.1.8886.1.18.2.1.1.1.16} # raisecomOpticalTransceiverWavelength, value in nm

  - {name: sfp.ddmValues, oid: .1.3.6.1.4.1.8886.1.18.2.2.1.1.2} 
  # .1.3.6.1.4.1.8886.1.18.2.2.1.1.2.{iface_id}.1 - Temperature. Divide value by 1000 to get in Celsius degrees 
  # .1.3.6.1.4.1.8886.1.18.2.2.1.1.2.{iface_id}.2 - Tx bias Current. Divide value by 1000 to get in mA
  # .1.3.6.1.4.1.8886.1.18.2.2.1.1.2.{iface_id}.3 - Optical Tx Power. Divide value by 1000 to get in dBm
  # .1.3.6.1.4.1.8886.1.18.2.2.1.1.2.{iface_id}.4 - Optical Rx Power. Divide value by 1000 to get in dBm
  # .1.3.6.1.4.1.8886.1.18.2.2.1.1.2.{iface_id}.5 - Supply Voltage. Divide value by 1000 to get in Volts