#ONT BLOCK
- {name: pon.opticalOltRx, oid: .1.3.6.1.4.1.3320.101.108.1.3 }
- {name: ont.opticalRx, oid: .1.3.6.1.4.1.3320.101.10.5.1.5 } # ONU PON port optical receive power. Unit is 0.1dB.
- {name: ont.opticalTx, oid: .1.3.6.1.4.1.3320.101.10.5.1.6 } # ONU PON port optical send power. Unit is 0.1dB.
- {name: ont.opticalVoltage, oid: .1.3.6.1.4.1.3320.101.10.5.1.3 } #ONU PON port optical module volt. Unit is 100uV.
- {name: ont.opticalTemp, oid: .1.3.6.1.4.1.3320.101.10.5.1.2 } #ONU PON port optical module temperature. Unit is 1/256 Celsuis.
- {name: ont.macAddr, oid: .1.3.6.1.4.1.3320.101.10.1.1.3 }
- {name: ont.distance, oid: .1.3.6.1.4.1.3320.101.10.1.1.27 }
- {name: ont.verSoftware, oid: .1.3.6.1.4.1.3320.101.10.1.1.6 }
- {name: ont.verHardware, oid: .1.3.6.1.4.1.3320.101.10.1.1.4 }
- {name: ont.vendor, oid: .1.3.6.1.4.1.3320.101.10.1.1.1 }
- {name: ont.model, oid: .1.3.6.1.4.1.3320.101.10.1.1.2 }
- {name: ont.bindType, oid: .1.3.6.1.4.1.3320.101.10.1.1.28, values: {0: Static, 1: Dynamic}}
- {name: ont.status, oid: .1.3.6.1.4.1.3320.101.10.1.1.26, values: {0: authenticated, 1: registered, 2: Offline, 3: Online, 4: LOS, 5: stand-by }}
- {name: ont.ipAddress, oid: .1.3.6.1.4.1.3320.101.10.4.1.2}
- {name: ont.aliveTime, oid: .1.3.6.1.4.1.3320.101.10.1.1.80}
- {name: ont.gePortCount, oid: .1.3.6.1.4.1.3320.101.10.1.1.12}
- {name: ont.gePortDistributing, oid: .1.3.6.1.4.1.3320.101.10.1.1.13}
- {name: ont.fePortCount, oid: .1.3.6.1.4.1.3320.101.10.1.1.14}
- {name: ont.fePortDistributing, oid: .1.3.6.1.4.1.3320.101.10.1.1.15}

# Номер ОНУ в дереве по мак-адресу (мак-адрес как часть оид)
- {name: ont.llidSeqNumber, oid: .1.3.6.1.4.1.3320.101.11.1.1.2}
- {name: ont.llidBindType, oid: .1.3.6.1.4.1.3320.101.11.1.1.5, values: {0: Static, 1: Dynamic } }
- {name: ont.llidBindStatus, oid: .1.3.6.1.4.1.3320.101.11.1.1.6, values: {0: authenticated, 1: registered, 2: deregistered, 3: discovered, 4: lost, 5: auto-configured } }
- {name: ont.llidBindDistance, oid: .1.3.6.1.4.1.3320.101.11.1.1.7}
- {name: ont.llidBindRTT, oid: .1.3.6.1.4.1.3320.101.11.1.1.8}

#  DateAndTime (OCTET STRING) (SIZE (8 |11)). Hint: 2d-1d-1d,1d:1d:1d.1d,1a1d:1d
# Парсить нужно как массив байт
# b[0:1] - год
# b[2] - месяц
# b[3] - день
# b[4] - час
# b[5] - минута
# b[6] - секунда
- {name: ont.llidLastRegTime, oid: .1.3.6.1.4.1.3320.101.11.1.1.9}
- {name: ont.llidLastDeregTime, oid: .1.3.6.1.4.1.3320.101.11.1.1.10}
- {name: ont.llidLastDeregReason, oid: .1.3.6.1.4.1.3320.101.11.1.1.11, values: {0: unknown, 2: normal, 3: mpcp-down, 4: oam-down, 5: firmware-download, 6: illegal-mac, 7: admin-down, 8: LOS, 9: PowerOff}}


- {name: resources.cpuUtil, oid: .1.3.6.1.4.1.3320.3.6.10.1.11}
#- {name: resources.cpuUsage5sec, oid: .1.3.6.1.4.1.3320.9.109.1.1.1.1.3}
#- {name: resources.cpuUsage1min, oid: .1.3.6.1.4.1.3320.9.109.1.1.1.1.4}
#- {name: resources.cpuUsage5min, oid: .1.3.6.1.4.1.3320.9.109.1.1.1.1.5}
- {name: resources.memUtil, oid: .1.3.6.1.4.1.3320.3.6.10.1.12}
- {name: resources.temperature.cpu, oid: .1.3.6.1.4.1.3320.3.6.10.1.13}
#- {name: resources.voltage, oid: .1.3.6.1.4.1.3320.3.6.10.1.14}
- {name: resources.fanStatus, oid: .1.3.6.1.4.1.3320.9.187.4.1.2, values: {1: Normal, 2: Stop, 3: Unused}}
#- {name: resources.fanSpeed, oid: .1.3.6.1.4.1.3320.9.187.4.1.3}

#- {name: sys.boardDescr, oid: .1.3.6.1.4.1.3320.3.6.10.1.3} #Not used
- {name: sys.serialNum, oid: .1.3.6.1.4.1.3320.9.225.1.2.0}
- {name: sys.boardHardwareVer, oid: .1.3.6.1.4.1.3320.9.225.1.7.0}
- {name: sys.boardSoftwareVer, oid: .1.3.6.1.4.1.3320.9.225.1.8.0}
- {name: sys.macAddress, oid: .1.3.6.1.4.1.3320.9.225.1.9.0}

- {name: vlan.list, oid: .1.3.6.1.2.1.17.7.1.4.2.1.2.0}
- {name: vlan.tagged, oid: .1.3.6.1.2.1.17.7.1.4.2.1.4}
- {name: vlan.untagged, oid: .1.3.6.1.2.1.17.7.1.4.2.1.5}

#FDB INFO

# SUPPORTED ONLY ON P3310C
- {name: pon.portStatus, oid: .1.3.6.1.4.1.3320.101.107.1.2, values: { 1: Up, 2: Down } }
- {name: pon.port.optical.temp, oid: .1.3.6.1.4.1.3320.101.107.1.6 } # Optical module temperature. The unit is 1/256 degree.
- {name: pon.port.optical.voltage, oid: .1.3.6.1.4.1.3320.101.107.1.7 } # Optical module volt. The unit is 0.1mV.
- {name: pon.port.optical.bias, oid: .1.3.6.1.4.1.3320.101.107.1.8 } # Optical module bias current. The unit is 2mA.
- {name: pon.port.optical.txPower, oid: .1.3.6.1.4.1.3320.101.107.1.3 }
- {name: pon.portDownOnuNum, oid: .1.3.6.1.4.1.3320.101.6.1.1.22}
- {name: pon.llIdIndexString, oid: .1.3.6.1.4.1.3320.101.6.1.1.23}


- {name: pon.portAdminStatus, oid: .1.3.6.1.4.1.3320.101.6.1.1.9, values: {1: Enabled, 2: Disabled}} #SNMPSET
- {name: pon.portCountOnu, oid: 1.3.6.1.4.1.3320.101.6.1.1.2}
- {name: pon.portMaxOnuNumSupport, oid: .1.3.6.1.4.1.3320.101.6.1.1.20}

#SNMP ACTIONS
- {name: olt.save, oid: .1.3.6.1.4.1.3320.20.15.1.1.0, values: {1: Action}}
- {name: ont.action.resetOnu, oid: .1.3.6.1.4.1.3320.101.10.1.1.29, values: {0: Reset, 1: NoReset}}

#UNI Block
- {name: ont.uni.opStatus, oid: .1.3.6.1.4.1.3320.101.12.1.1.8, values: {1: Up, 2: Down}}
- {name: ont.uni.adminStatus, oid:  .1.3.6.1.4.1.3320.101.12.1.1.7, values: {1: Enabled, 2: Disabled}}
- {name: ont.uni.operMode, oid:  .1.3.6.1.4.1.3320.101.12.1.1.9, values: {1: Full, 2: Half, 3: Auto}}
- {name: ont.uni.speed, oid:  .1.3.6.1.4.1.3320.101.12.1.1.10, values: {1: 10, 2: 100, 3: 1G, 4: Auto}}
- {name: ont.uni.pvid, oid: .1.3.6.1.4.1.3320.101.12.1.1.3 } #Allow to set pvid
- {name: ont.uni.flowControlStatus, oid: .1.3.6.1.4.1.3320.101.12.1.1.11, values: {1: Enabled, 2: Disabled} }
- {name: ont.uni.pvidMode, oid: .1.3.6.1.4.1.3320.101.12.1.1.18, values: {0: Transparent, 1: Tagged, 2: Translation, 3: Aggregation, 4: Trunk, 5: Stacking }}
- {name: ont.uni.statInOctets, oid: .1.3.6.1.4.1.3320.101.12.2.1.3}
- {name: ont.uni.statInBadOctects, oid: .1.3.6.1.4.1.3320.101.12.2.1.4}
- {name: ont.uni.statInBroadcasts, oid: .1.3.6.1.4.1.3320.101.12.2.1.5}
- {name: ont.uni.statInMulticasts, oid: .1.3.6.1.4.1.3320.101.12.2.1.6}
- {name: ont.uni.statInUnicasts, oid: .1.3.6.1.4.1.3320.101.12.2.1.7}
#- {name: ont.uni.statInPause, oid: .1.3.6.1.4.1.3320.101.12.2.1.8}
- {name: ont.uni.statInMACRcvErr, oid: .1.3.6.1.4.1.3320.101.12.2.1.9}
- {name: ont.uni.statInCRC, oid: .1.3.6.1.4.1.3320.101.12.2.1.10}
#- {name: ont.uni.statUndersize, oid: .1.3.6.1.4.1.3320.101.12.2.1.11}
#- {name: ont.uni.statFragments, oid: .1.3.6.1.4.1.3320.101.12.2.1.12}
#- {name: ont.uni.statOversize, oid: .1.3.6.1.4.1.3320.101.12.2.1.13}
#- {name: ont.uni.statJabber, oid: .1.3.6.1.4.1.3320.101.12.2.1.14}
- {name: ont.uni.statOutOctets, oid: .1.3.6.1.4.1.3320.101.12.2.1.15}
- {name: ont.uni.statOutBroadcasts, oid: .1.3.6.1.4.1.3320.101.12.2.1.16}
- {name: ont.uni.statOutMulticasts, oid: .1.3.6.1.4.1.3320.101.12.2.1.17}
- {name: ont.uni.statOutUnicasts, oid: .1.3.6.1.4.1.3320.101.12.2.1.18}
#- {name: ont.uni.statOutPause, oid: .1.3.6.1.4.1.3320.101.12.2.1.19}
- {name: ont.uni.statOutCRC, oid: .1.3.6.1.4.1.3320.101.12.2.1.20}
#- {name: ont.uni.statDeferred, oid: .1.3.6.1.4.1.3320.101.12.2.1.21}
#- {name: ont.uni.statExcessive, oid: .1.3.6.1.4.1.3320.101.12.2.1.22}
#- {name: ont.uni.statSingle, oid: .1.3.6.1.4.1.3320.101.12.2.1.23}
#- {name: ont.uni.statMultiple, oid: .1.3.6.1.4.1.3320.101.12.2.1.24}
#- {name: ont.uni.statLate, oid: .1.3.6.1.4.1.3320.101.12.2.1.25}
- {name: ont.uni.statCollisions, oid: .1.3.6.1.4.1.3320.101.12.2.1.26}

# Получение скоростей на ОНУ
- {name: ont.bandwidthTxPIR, oid: .1.3.6.1.4.1.3320.101.9.1.1.8}
- {name: ont.bandwidthTxCIR, oid: .1.3.6.1.4.1.3320.101.9.1.1.9 }
- {name: ont.bandwidthTxFIR, oid: .1.3.6.1.4.1.3320.101.9.1.1.10 }

- {name: ont.bandwidthRxPIR, oid: .1.3.6.1.4.1.3320.101.9.1.1.17 }
- {name: ont.bandwidthRxCIR, oid: .1.3.6.1.4.1.3320.101.9.1.1.18 }
- {name: ont.bandwidthRxFIR, oid: .1.3.6.1.4.1.3320.101.9.1.1.19 }



