- {name: sys.boardName, oid: .1.3.6.1.4.1.2011.6.1.1.1.1.3}
- {name: sys.version, oid: .1.3.6.1.4.1.2011.6.3.1.3.0}
- {name: sys.slot.description, oid: .1.3.6.1.4.1.2011.6.3.3.2.1.3}
- {name: sys.slot.typeName, oid: .1.3.6.1.4.1.2011.6.3.3.2.1.21}
- {name: sys.slot.serial, oid: .1.3.6.1.4.1.2011.6.3.3.2.1.11}
- {name: sys.slot.sub.countPorts, oid: .1.3.6.1.4.1.2011.6.3.3.3.1.3}
- {name: sys.slot.operStatus, oid: .1.3.6.1.4.1.2011.6.3.3.2.1.8, values: {1: online,
                                                                           2: normal,
                                                                           3: fault,
                                                                           4: forbidden,
                                                                           5: autofind,
                                                                           6: config,
                                                                           7: offline,
                                                                           8: abnormal,
                                                                           9: versionerr,
                                                                           10: autoload,
                                                                           11: outofservice,
                                                                           12: graceful,
                                                                           13: shutdown,
                                                                           14: energysavingshutdown,
                                                                           15: hightempshutdown,
                                                                           16: manualshutdown,
                                                                           17: mismatch,
                                                                           18: acoffshutdown,}}
- {name: sys.slot.adminState, oid: .1.3.6.1.4.1.2011.6.3.3.2.1.9, values: {-1: nooperation,
                                              1: disable,
                                              2: enable,
                                              3: reset,
                                              4: test,
                                              5: confirm,
                                              6: switch,
                                              7: delete,
                                              8: forbidden,
                                              9: unforbidden,
                                              10: endservice,
                                              11: startservice,
                                              12: poweron,
                                              13: poweroff,
                                              14: is,
                                              15: oos}}

- {name: sys.slot.cpuUtil, oid: 1.3.6.1.4.1.2011.2.6.7.1.1.2.1.5 }
- {name: sys.slot.temp, oid: 1.3.6.1.4.1.2011.6.3.3.2.1.13 }
- {name: resources.temp, oid: .1.3.6.1.4.1.2011.6.1.1.5.1.7}
- {name: fan.controlMode, oid: .1.3.6.1.4.1.2011.6.1.1.5.1.2, values: {1: Manual, 2: EmuAuto, 3: Fixed, 4: MainboardAuto}}
- {name: fan.speed, oid: .1.3.6.1.4.1.2011.6.1.1.5.1.9}

- {name: ont.status, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.15, values: {1: Online, 2: Offline, -1: Invalid}}
- {name: ont.confStatus, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.16, values: {1: Initialization, 2: Normal, 3: Failed, 4: NoResume, 5: Config, -1: Invalid}}
- {name: ont.discoveryStatus, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.17, values: {1: On, 2: Off, -1: Invalid}}
- {name: ont.stat.outOctets, oid: .1.3.6.1.4.1.2011.6.128.1.1.4.23.1.3}
- {name: ont.stat.inOctets, oid: .1.3.6.1.4.1.2011.6.128.1.1.4.23.1.4}
- {name: ont.stat.outDropPkts, oid: .1.3.6.1.4.1.2011.6.128.1.1.4.23.1.5}
- {name: ont.stat.inDropPkts, oid: .1.3.6.1.4.1.2011.6.128.1.1.4.23.1.6}
- {name: ont.stat.reset, oid: .1.3.6.1.4.1.2011.6.128.1.1.4.23.1.20, values: {1: Reset}}

- {name: ont.vendor.hardwareVer, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.45.1.1}
- {name: ont.vendor.equipmentId, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.45.1.4}
- {name: ont.vendor.softwareVer, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.45.1.5}

- {name: ont.config.authMethod, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.2, values: {1: SN, 2: SN-Password, 3: AlwaysOn, 4: OnceOn, 5: LOID-AlwaysOn, 6: LOID-OnceOn, 7: LOID-CheckCode-AlwaysOn, 8: LOID-CheckCode-OnceOn, -1: Invalid}}
- {name: ont.config.sn, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.3}
- {name: ont.config.password, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.4}
- {name: ont.config.timeout, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.5}
- {name: ont.config.lineProfileName, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.7}
- {name: ont.config.serviceProfileName, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.8}
- {name: ont.config.description, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.43.1.9}
- {name: ont.config.isolationState, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.26, values: {0: Normal, 1: Isolated}}


# ONT IP configuration
- {name: ont.config.ip.mode, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.1, values: {1: DHCP, 2: Static, 3: Unconfiguration, 4: ConfigurationFile, -1: Invalid}}
- {name: ont.config.ip.ipAddress, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.2}
- {name: ont.config.ip.netMask, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.3}
- {name: ont.config.ip.physAddress, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.4}
- {name: ont.config.ip.netGw, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.5}
- {name: ont.config.ip.DNS1, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.6}
- {name: ont.config.ip.DNS2, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.7}
- {name: ont.config.ip.vlanId, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.8}
- {name: ont.config.ip.resetDHCP, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.49.1.13, values: {1: Reset}}


# In Huawei is  hwGponDeviceOntControlRanging
- {name: ont.distance, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.20}
- {name: ont.opticalTemp, oid:  .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.1 }
- {name: ont.opticalBias, oid:  .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.2 }
- {name: ont.opticalTx, oid:  .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.3 } # value / 100 = dB
- {name: ont.opticalRx, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.4 } # value / 100 = dB
- {name: ont.opticalOltRx, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.6 } # value / 100 = dB
- {name: ont.opticalVoltage, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.51.1.5 } # value / 100 = volt

# DateAndTime (OCTET STRING) (SIZE (8 |11)). Hint: 2d-1d-1d,1d:1d:1d.1d,1a1d:1d
- {name: ont.lastUptime, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.22}
- {name: ont.lastDownTime, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.23}

#This object indicates the reason why the ONT last went offline.
#The value (1) indicates that the reason is LOS(Loss of signal),
#The value (2) indicates that the reason is LOSI(Loss of signal for ONUi),
#The value (3) indicates that the reason is LOFI(Loss of frame of ONUi),
#The value (4) indicates that the reason is SFI(Signal fail of ONUi),
#The value (5) indicates that the reason is LOAI(Loss of acknowledge with ONUi),
#The value (6) indicates that the reason is LOAMI(Loss of PLOAM for ONUi),
#The value (7) indicates that the reason is deactive ONT fails,
#The value (8) indicates that the reason is deactive ONT success,
#The value (9) indicates that the reason is reset ONT,
#The value (10) indicates that the reason is re-register ONT,
#The value (11) indicates that the reason is pop up fail,
#The value (13) indicates that the reason is dying-gasp,
#The value (15) indicates that the reason is LOKI(Loss of key synch with ONUi),
#The value (-1) indicates that the query fails.
- {name: ont.lastDownCause, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.24, values: {1: LOS, 2: LOSi, 3: LOFi, 4: SFI, 5: LOAI, 6: LOAMI, 7: DeactivateFail, 8: Deactivated, 9: Reset, 10: ReRegister, 11: PopUpFail, 13: PowerOff, 15: LOKI, -1: Unknown, 18: Unknown}}

#For build table down-up-downReason
- {name: ont.regTable.uptime, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.101.1.6}
- {name: ont.regTable.downTime, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.101.1.7}
- {name: ont.regTable.downCause, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.101.1.8, values: {0: Deleted, 1: LinkedDown, 2: LOSi, 3: LOFi, 4: SFI, 5: LOAI, 6: LOAMI, 7: DisableFail, 8: Deactivated, 9: Reset, 10: ReRegister, 11: PopUpFail, 12: AuthFail, 13: PowerDown, 14: Reserved, 15: Loki, 255: NoError, -1: Invalid}}


#  This object indicates the ONT battery status.
#Options:
#1. notSupport(0)         - Not support
#2. charge(1)             - Charge state
#3. discharge(2)          - Discharge state
#4. holding(3)            - Holding state
#5. supportButInvalid(4)  - Provisioned and present but cannot recharge
#6. unknownStatus(-1)     - Indicates that the query fails or no information is detected
- {name: ont.batteryStatus, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.27, values: {0: NotSupported, 1: Charge, 2: Discharge, 3: Holding, 4: SupportButInvalid, -1: Unknown}}

#This object is used to activate or deactivate an ONT
- {name: ont.controlActive, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.1, values: {1: Activate, 2: Deactivate, -1: Invalid}}
#This object is used to reset an ONT.
- {name: ont.controlReset, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.2, values: {1: Reset}}
#This object is used to re-register an ONT.
- {name: ont.controlReRegister, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.3, values: {1: ReRegister}}
#This object is used to reset the discovery status of an ONT
- {name: ont.controlReDiscovery, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.46.1.4, values: {1: ReDiscovery}}


- {name: ont.autofind.sn, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.2}
- {name: ont.autofind.password, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.3}
- {name: ont.autofind.version, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.5}
- {name: ont.autofind.softwareVer, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.6}
- {name: ont.autofind.equipmentId, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.7}
- {name: ont.autofind.checkCode, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.10}
- {name: ont.autofind.loid, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.48.1.9}

#UNI = Eth ports on ONU.
- {name: uni.configure.duplex, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.3, values: {1: Half, 2: Full, 3: Auto, 4: Auto-Half, 5: Auto-Full, -1: Invalid}}
- {name: uni.configure.speed, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.4, values: {1: 10M, 2: 100M, 3: 1G, 4: Auto, 5: Auto-10M, 6: Auto-100M, 7: Auto-1G, -1: Invalid}}
- {name: uni.configure.state, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.5, values: {1: Enabled, 2: Disabled}}
- {name: uni.configure.flowControl, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.6, values: {1: On, 2: Off}}
- {name: uni.configure.vlan, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.7}
- {name: uni.type, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.21, values: {24: FE, 34: GE, 50: IpHost, 47: Eth}}
- {name: uni.status, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.62.1.22, values: {1: Up, 2: Down}}

- {name: pon.optical.temp, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.23.1.1}
- {name: pon.optical.voltage, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.23.1.2}
- {name: pon.optical.bias, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.23.1.3}
- {name: pon.optical.tx, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.23.1.4}

- {name: pon.vendor.name, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.22.1.11}
- {name: pon.vendor.sn, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.22.1.20}
- {name: pon.vendor.xponType, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.22.1.27, values: {1: Unknown, 2: GPON, 3: EPON, 4: EPON-10G, 5: GPON-10G, 6: WDM-PON, 7: Hybrid-PON, -1: Invalid}}
- {name: pon.optical.tx, oid: .1.3.6.1.4.1.2011.6.128.1.1.2.23.1.4}

#Profile name must parse from OID
- {name: gpon.profiles.line.bindNum, oid: .1.3.6.1.4.1.2011.6.128.1.1.3.61.1.2}
- {name: gpon.profiles.srv.bindNum, oid: .1.3.6.1.4.1.2011.6.128.1.1.3.65.1.2}
