- name: onuOnlineStatusChange
  description: Online status changed
  object: .1.3.6.1.4.1.34592.1.3.6.0.7
  is_interface: true
  modules:
    - pon_onts_status

- name:  onuPortLoopBack
  description: Port loopback detected
  object: .1.3.6.1.4.1.34592.1.3.6.0.18
  is_interface: true

- name: powerStatusChange
  description: Power status changed
  object: .1.3.6.1.4.1.34592.1.3.6.0.3
  is_interface: true

- name:  fanStatusChange
  description: Fan status changed
  object: .1.3.6.1.4.1.34592.1.3.6.0.4
  is_interface: true
