- name: LinkUp
  description: |
      A linkUp trap signifies that the SNMPv2 entity,
      acting in an agent role, has detected that the
      ifOperStatus object for one of its communication links
      has transitioned out of the down state.
  object: .1.3.6.1.6.3.1.1.5.4
  is_interface: true
  modules:
    - link_info

- name: LinkDown
  description: |
    A linkDown trap signifies that the SNMPv2 entity,
    acting in an agent role, has detected that the
    ifOperStatus object for one of its communication links
    is about to transition into the down state.
  object: .1.3.6.1.6.3.1.1.5.3
  is_interface: true
  modules:
    - link_info
