- name:  GponProfOntAutoFindTrap
  description: |
    This trap is sent when the ONT reports the ONT type and version information
    during the ONT automatic discovery.
  object: .1.3.6.1.4.1.2011.6.128.1.1.12.3.0.2
  modules:
    - unregistered_onts
  is_interface: true

- name: EponProfOntAutoFindTrap
  description: |
    This trap is sent when the ONT type and capability in the ONT automatic discovery.
  object: .1.3.6.1.4.1.2011.6.128.1.1.12.3.0.50
  modules:
    - unregistered_onts
  is_interface: true

- name: hwXponProfOntPortStatusTrap
  description: |
    This trap is sent when the status of the ONT port changes.
  object: .1.3.6.1.4.1.2011.6.128.1.1.12.3.0.51
  modules:
    - unregistered_onts
  is_interface: true

- name: hwEponConfigChangeOntDiscTrap
  description: |
    This trap is sent when the discovery status of the ONT changes.
  object: .1.3.6.1.4.1.2011.6.128.1.1.12.3.0.104
  is_interface: true

