<?php


namespace SwitcherCore\Modules\ZTE\C600Series;


use Exception;
use SnmpWrapper\Oid;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Switcher\Objects\WrappedResponse;

class CtrlOntDisable extends ModuleAbstract
{
    /**
     * @var WrappedResponse[]
     */
    protected $response = true;

    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        $iface = $this->parseInterface($filter['interface']);
        if(!preg_match('/^.*([0-9])\/([0-9]{1,4}):([0-9]{1,3})$/', $iface['name'], $match)) {
            throw new \InvalidArgumentException("Error parse ONT interface");
        }
        $state = null;
        $oid = $this->oids->getOidByName('gpon.ont.adminState');

        switch ($filter['state']) {
            case 'enable': $state = 1; break;
            case 'disable': $state = 2; break;
        }
        if(!$state) {
            throw new \Exception("Error find state integer value for {$filter['state']}");
        }

        $this->checkSnmpRespError($this->snmp->set(
            Oid::init($oid->getOid() . ".{$iface['_oid_id']}")
                ->setType('Integer')
                ->setValue($state)
        ));
        return $this;
    }

    function getPretty()
    {
        return true; // TODO: Change the autogenerated stub
    }

    function getPrettyFiltered($filter = [])
    {
        return $this->response;
    }
}

