<?php

namespace SwitcherCore\Modules\Edgecore;

class InterfacesList extends \SwitcherCore\Modules\General\Switches\InterfacesList
{
    use InterfacesTrait;
    public function getPrettyFiltered($filter = [])
    {
        return parent::getPrettyFiltered($filter); // TODO: Change the autogenerated stub
    }
}
