- {name: sys.serialNum, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.5.11}
- {name: sys.boardHardwareVer, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.5.5}
- {name: sys.boardSoftwareVer, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.5.4}
- {name: sys.macAddress, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.5.7}
- {name: sys.hostName, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.5.1}


- {name: resources.cpuUtil, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.3.0}
- {name: resources.memUtil, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.4.0}
- {name: resources.temperature.cpu, oid: .1.3.6.1.4.1.37950.1.1.5.10.12.5.9.0}

- {name: pon.port.optical.temp, oid: .1.3.6.1.4.1.37950.1.1.5.10.13.1.1.2}
- {name: pon.port.optical.voltage, oid: .1.3.6.1.4.1.37950.1.1.5.10.13.1.1.3}
- {name: pon.port.optical.txPower, oid: .1.3.6.1.4.1.37950.1.1.5.10.13.1.1.5}
- {name: pon.portCountOnu, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.18.1.2}
- {name: pon.portCountOnlineOnts, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.18.1.3}
- {name: pon.port.sfp.txPower, oid: 1.3.6.1.4.1.37950.1.1.5.10.13.1.1.4}

# last_index=ONU number, last_index-1=PON port number, ont.status 4: dyingGasp
#  INTEGER {logging(0),
#los(1),
#syncMib(2),
#working(3),
#dyingGasp(4),
#authFail(5),
#offLine(6),
#deactivated(7),
#configFail(8)
#}
- {name: ont.status, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.1.1.5, values: {0: Logging, 2: SyncMib, 3: Online, 4: PowerOff, 5: AuthFail, 6: Offline, 7: Disabled, 8: ConfigFail}}

- {name: ont.serial, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.2.1.5}

- {name: ont.actions.port, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.5.1.0}
- {name: ont.actions.ont, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.5.2.0}
- {name: ont.actions.action, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.5.3.0, values: {1: reboot, 2: delete, 3: enable, 4: disable}}

- {name: ont.description, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.4.1.24}
- {name: ont.vendor, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.4.1.3}
- {name: ont.model, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.4.1.14}
- {name: ont.onuId, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.2.1.5}
- {name: ont.hardwareVer, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.4.1.4}
- {name: ont.softwareVer, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.4.1.25}

- {name: ont.optical.distance, oid: 1.3.6.1.4.1.37950.1.1.6.1.1.12.1.3}
- {name: ont.optical.temp, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.3.1.3}
- {name: ont.optical.voltage, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.3.1.4}
- {name: ont.optical.txBias, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.3.1.5}
- {name: ont.optical.txPower, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.3.1.6}
- {name: ont.optical.rxPower, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.3.1.7}

# Настройка UNI портов
- {name: uni.control.set.ponNum, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.7.8.1.0}
- {name: uni.control.set.onuNum, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.7.8.2.0}
- {name: uni.control.set.portNum, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.7.8.3.0}
- {name: uni.control.set.adminStatus, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.7.8.4.0, values: {0: Enabled, 1: Disabled}}

# Инфо о UNI-порте
- {name: ont.uni.status, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.8.15.1.4, values: {0: Up, 1: Down}}
- {name: ont.uni.adminStatus, oid: .1.3.6.1.4.1.37950.1.1.6.1.1.8.15.1.6, values: {1: Down, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Full, 7: 1G-Half}}

# UNI версия 2
# Скорость .1.3.6.1.4.1.37950.1.1.6.1.1.8.15.1.6
#  INTEGER {auto(1),
#half10(2),
#full10(3),
#half100(4),
#full100(5),
#full1000(6),
#half1000(7)
#}

# Cтатус порта - .1.3.6.1.4.1.37950.1.1.6.1.1.8.15.1.4 (0-включен, 1-выключен)


#  INTEGER {update(1),
#active(2),
#commit(3),
#update-and-reboot(4),
#quick_active(6)
#}
- {name: ont.up.statusAction, oid: .1.3.6.1.4.1.37950.1.1.6.1.4.7.1.3}
- {name: ont.up.status, oid: .1.3.6.1.4.1.37950.1.1.6.1.4.7.1.4}
- {name: ont.up.failReason, oid: .1.3.6.1.4.1.37950.1.1.6.1.4.7.1.6}
- {name: ont.up.commitTime, oid: .1.3.6.1.4.1.37950.1.1.6.1.4.7.1.7}