<?php


namespace SwitcherCore\Modules\CData\FD16xxV3;


use Exception;
use SnmpWrapper\Oid;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Switcher\Objects\WrappedResponse;

class CtrlOntDescription extends CDataAbstractModuleFD16xxV3
{
    /**
     * @var WrappedResponse[]
     */
    protected $response = true ;

    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        $iface = $this->parseInterface($filter['interface']);

        if(!preg_match('/^[A-Za-z0-9_-]{1,}$/', $filter['description'])) {
            throw new \Exception("Incorrect description format");
        }

        $commands = [
            'interface gpon 0/0',
            "ont description {$iface['_port']} {$iface['_onu']} {$filter['description']}",
            "exit"
        ];
        $responses = $this->getModule('multi_console_command')->run([
            'commands' => $commands,
            'break_on_error' => 'yes',
        ])->getPrettyFiltered([]);
        if (count(array_filter($responses, function ($response) {
                return !$response['success'];
            })) != 0) {
            throw new Exception("Error running commands for change ONU description", 1);
        }

        $this->response = true;
        return $this;
    }

    function getPretty()
    {
        return true; // TODO: Change the autogenerated stub
    }
}

