<?php


namespace SwitcherCore\Modules\CData\FD16xxV3;


use Exception;
use SnmpWrapper\Oid;
use SnmpWrapper\Response\PoollerResponse;
use SnmpWrapper\Response\SnmpResponse;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Modules\Helper;
use SwitcherCore\Switcher\Objects\WrappedResponse;


/**
 * Class OntUniInformation
 * @package SwitcherCore\Modules\CData\FD16xxV3
 */
class EponOntInterfaceCounters extends CDataAbstractModuleFD16xxV3
{
    /**
     * @var WrappedResponse[]
     */
    protected $response = null ;
    function getRaw()
    {
        return $this->response;
    }
    function getPrettyFiltered($filter = [], $fromCache = false)
    {
        return parent::getPrettyFiltered($filter); // TODO: Change the autogenerated stub
    }

    /**
     * @param WrappedResponse[] $response
     * @return array
     */
    private function process($response) {
        $interfaces = [];
        foreach ($response as $name=>$data) {
            if($data->error()) {
                throw new \SNMPException($data->error());
            }
            foreach ($data->fetchAll() as $r) {
                $xid = Helper::getIndexByOid($r->getOid());
                try {
                    $interfaces[$xid]['interface'] = $this->parseInterface($xid);
                    if(!isset($interfaces[$xid])) continue;
                    switch ($name) {
                        case 'if.InErrors':
                            $interfaces[$xid]['in_errors'] = (int)$r->getValue();
                            break;
                        case 'if.OutErrors':
                            $interfaces[$xid]['out_errors'] = (int)$r->getValue();
                            break;
                        case 'if.InDiscards':
                            $interfaces[$xid]['in_discards'] = (int)$r->getValue();
                            break;
                        case 'if.OutDiscards':
                            $interfaces[$xid]['out_discards'] = (int)$r->getValue();
                            break;
                        case 'if.HCInOctets':
                            $interfaces[$xid]['in_octets'] = (int)$r->getValue();
                            break;
                        case 'if.HCOutOctets':
                            $interfaces[$xid]['out_octets'] = (int)$r->getValue();
                            break;
                        case 'if.HCOutMulticastPkts':
                            $interfaces[$xid]['out_multicast_pkts'] = (int)$r->getValue();
                            break;
                        case 'if.HCInMulticastPkts':
                            $interfaces[$xid]['in_multicast_pkts'] = (int)$r->getValue();
                            break;
                        case 'if.HCOutBroadcastPkts':
                            $interfaces[$xid]['out_broadcast_pkts'] = (int)$r->getValue();
                            break;
                        case 'if.HCInBroadcastPkts':
                            $interfaces[$xid]['in_broadcast_pkts'] = (int)$r->getValue();
                            break;
                    }
                } catch (\Exception $e) {}
            }
        }
        return array_values(array_filter($interfaces, function ($iface) {
           return
               isset($iface['in_octets']) &&
               isset($iface['out_octets']) &&
               isset($iface['in_errors']) &&
               isset($iface['out_errors']);
        }));
    }


    function getPretty()
    {
        return $this->response;
    }


    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        $oids = [
            $this->oids->getOidByName('if.InErrors'),
            $this->oids->getOidByName('if.InErrors'),
            $this->oids->getOidByName('if.OutErrors'),
            $this->oids->getOidByName('if.InDiscards'),
            $this->oids->getOidByName('if.OutDiscards'),
            $this->oids->getOidByName('if.HCInOctets'),
            $this->oids->getOidByName('if.HCOutOctets'),
        ];
        if($filter['interface']) {
            $interface = $this->parseInterface($filter['interface']);
            $oids = array_map(function ($o) use ($interface) {
                return  Oid::init($o->getOid() . '.' . $interface['id']);
            }, $oids);
            $this->response = $this->process($this->formatResponse($this->snmp->get($oids)));
        } else {
            $oids = array_map(function ($o)  {
                return  Oid::init($o->getOid() );
            }, $oids);
            $this->response = $this->process($this->formatResponse($this->snmp->walkNext($oids)));
        }
        return $this;
    }


}

