<?php


namespace SwitcherCore\Modules\BDcom\GP3600;


use Exception;
use SwitcherCore\Config\Objects\Oid;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Modules\Helper;
use SwitcherCore\Switcher\Objects\SnmpResponse;
use SwitcherCore\Switcher\Objects\WrappedResponse;

class UniInterfacesControlAdminStatus extends BDcomAbstractModule
{
    protected $response = null;


    function getPrettyFiltered($filter = [], $fromCache = false)
    {
        return true; // TODO: Change the autogenerated stub
    }


    function getPretty()
    {
        return true;
    }

    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        $iface = $this->parseInterface($filter['interface']);

        $action = null;
        switch ($filter['state']) {
            case 'enable': $action = 1; break;
            case 'disable': $action = 2; break;
        }

        $oid = \SnmpWrapper\Oid::init($this->oids->getOidByName('ont.uni.adminStatus')->getOid() . ".{$iface['xid']}.{$filter['num']}")
            ->setType('Integer')
            ->setValue($action);
        $this->snmp->set($oid);
        $this->response = true;
        return $this;
    }
}

