- {name: resources.cpuUtil, oid: .1.3.6.1.4.1.34592.1.3.1.1.8}
- {name: resources.temperature, oid: .1.3.6.1.4.1.34592.1.3.1.3.4}

- {name: sys.serialNum, oid: .1.3.6.1.4.1.34592.1.3.1.3.2}
- {name: sys.boardHardwareVer, oid: .1.3.6.1.4.1.34592.1.3.1.5.1.3}
- {name: sys.boardSoftwareVer, oid: .1.3.6.1.4.1.34592.1.3.1.5.1.4}

#FDB INFO
- {name: pon.fdbWithUni, oid: .1.3.6.1.4.1.34592.1.3.4.10.2.1.2.1}

# PON PORT BLOCK
  # OpTemp ..1.3.6.1.4.1.34592.1.3.100.2.2.1.4.1.0.9
  # where 1.0.9
  # 1 - device index (default=1)
  # 0 - card number (default=1)
  # 9 - number of port (stored in xid value in model extra parameters)
- {name: pon.portDmTemp, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.1}
- {name: pon.portDmVoltage, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.2}
- {name: pon.portDmTxBias, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.3}
- {name: pon.portDmTxPower, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.4}
#- {name: pon.portDmRxPower, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.5}
- {name: pon.portDmVendor, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.6}
- {name: pon.portDmProductName, oid: .1.3.6.1.4.1.34592.1.3.3.4.5.1.7}
- {name: pon.portOperStatus, oid: .1.3.6.1.4.1.34592.1.3.3.1.1.3, values: {1: Unknown, 2: Down, 3: Up}}
- {name: pon.countRegisteredOnts, oid: .1.3.6.1.4.1.34592.1.3.3.1.1.6}
- {name: pon.portMaxOnuNumSupport, oid: .1.3.6.1.4.1.34592.1.3.3.1.1.5}

#SNMP ACTIONS
- {name: olt.save, oid: .1.3.6.1.4.1.34592.1.3.1.2.12.0, values: {1: Action}}

#ONT BLOCK
- {name: ont.operation, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.32, values: {7: Dereg, }}
- {name: ont.opticalRx, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.36}
- {name: ont.opticalTx, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.37}
- {name: ont.opticalVoltage, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.38}
#- {name: ont.opticalTemp, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.40}
- {name: ont.macAddr, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.7}
- {name: ont.mgmtType, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.35, values: {1: TK, 2: CTC}}
- {name: ont.distance, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.13}
- {name: ont.name, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.4}
- {name: ont.verSoftware, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.6}
- {name: ont.verHardware, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.5}
- {name: ont.vendor, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.41}
- {name: ont.serial, oid: .1.3.6.1.4.1.34592.1.3.4.1.1.3}
- {name: pon.ontStatus, oid: .1.3.6.1.4.1.34592.1.3.3.14.1.1}

# LLID Block (Extendend info about ONU)
- {name: ont.llidAssociatedOnuId, oid: .1.3.6.1.4.1.34592.1.3.3.12.1.1.3}
- {name: ont.llidOperations, oid: .1.3.6.1.4.1.34592.1.3.3.12.1.1.10, values: {3: dereg, 4: breakCrossLink, 5: restoreConfig, 6: deleteLink}}

#UNI Block
- {name: ont.uni.description, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.2 }
- {name: ont.uni.opStatus, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.3, values: {1: Up, 2: Down}}
- {name: ont.uni.speed, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.5, values: {1: 10M, 2: 100M, 3: 1G}}
- {name: ont.uni.duplex, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.6, values: {1: Full, 2: Half}}
- {name: ont.uni.adminStatus, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.11, values: {1: Enabled, 2: Disabled}}
- {name: ont.uni.name, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.13}
- {name: ont.uni.type, oid: .1.3.6.1.4.1.34592.1.3.4.3.1.14, values: {1: Fe, 2: Ge, 3: PON}}
