- {name: resources.cpuUsage, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.1}
- {name: resources.memTotalSize, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.2}
- {name: resources.memFreeSize, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.3}
- {name: resources.temperature, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.6} # val / 100
- {name: resources.temperatureTreshhold, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.7}


- {name: sys.macAddr, oid: .1.3.6.1.4.1.17409.2.3.1.1.6}
- {name: sys.vendorName, oid: .1.3.6.1.4.1.17409.2.3.1.1.12}
- {name: sys.serialNum, oid: .1.3.6.1.4.1.17409.2.3.1.1.13}
- {name: sys.boardHardwareVer, oid: .1.3.6.1.4.1.17409.2.3.1.3.1.1.7.1}
- {name: sys.boardSoftwareVer, oid: .1.3.6.1.4.1.17409.2.3.1.3.1.1.9.1}
- {name: pon.countRegisteredOnts, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.8}
- {name: vlan.list, oid: .1.3.6.1.4.1.17409.2.3.7.2.1.1.3}
- {name: vlan.tagged, oid: .1.3.6.1.4.1.17409.2.3.7.2.1.1.4}
- {name: vlan.untagged, oid: .1.3.6.1.4.1.17409.2.3.7.2.1.1.5}

#FDB INFO
- {name: pon.fdbWithUni, oid: 1.3.6.1.4.1.34592.1.3.100.13.1.1.5}

# PON PORT BLOCK
  # OpTemp ..1.3.6.1.4.1.34592.1.3.100.2.2.1.4.1.0.9
  # where 1.0.9
  # 1 - device index (default=1)
  # 0 - card number (default=1)
  # 9 - number of port (stored in xid value in model extra parameters)
- {name: pon.portOperStatus, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.5, values: {1: Up, 2: Down, 3: Testing}}
- {name: pon.portAdminStatus, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.6, values: {1: Enabled, 2: Disabled}} #SNMPSET
- {name: pon.portMaxOnuNumSupport, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.7}
- {name: pon.portMaxDsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.12}
- {name: pon.portActualDsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.13}
- {name: pon.portRemainDsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.14}
- {name: pon.portMaxUsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.18}
- {name: pon.portActualUsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.19}
- {name: pon.portRemainUsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.20}
- {name: pon.portOpticalRxOfOnu, oid: .1.3.6.1.4.1.17409.2.3.3.6.1.2}

#SNMP ACTIONS
- {name: ont.action.reboot, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.17, values: {1: Action}}
- {name: olt.save, oid: .1.3.6.1.4.1.17409.2.3.1.1.14.0, values: {1: Action}}
- {name: ont.action.delete, oid: .1.3.6.1.4.1.17409.2.3.4.5.2.1.4, values: {6: Delete}}
#- {name: ont.action.setVlan, oid: .1.3.6.1.4.1.17409.2.3.7.3.1.1.7}
- {name: ont.action.resetOnu, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.17, values: {1: Reset}}
- {name: ont.action.clear_counters, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.48}

#ONT BLOCK
- {name: ont.description, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.2}
- {name: ont.opticalRx, oid: .1.3.6.1.4.1.17409.2.3.4.2.1.4}
- {name: ont.opticalTx, oid: .1.3.6.1.4.1.17409.2.3.4.2.1.5}
- {name: ont.opticalVoltage, oid: .1.3.6.1.4.1.17409.2.3.4.2.1.7}
- {name: ont.opticalTemp, oid: .1.3.6.1.4.1.17409.2.3.4.2.1.8}
- {name: ont.macAddr, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.7}
- {name: ont.distance, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.15}
- {name: ont.name, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.2}
- {name: ont.opStatus, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.8, values: {1: Up, 2: Down}}
- {name: ont.adminStatus, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.9, values: {1: Enabled, 2: Disabled}}
- {name: ont.verSoftware, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.13}
- {name: ont.verHardware, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.27}
- {name: ont.vendor, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.25}
- {name: ont.model, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.26}
- {name: ont.lastRegSince, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.18}
- {name: ont.lastDownReason, oid: .1.3.6.1.4.1.34592.1.3.100.12.3.1.1.7, values: {'dying-gasp': PowerOff, 'losi': LOS, '': Unknown}}
- {name: ont.lastDownSince, oid: .1.3.6.1.4.1.34592.1.3.100.12.3.1.1.6}
- {name: pon.ontStatus, oid: .1.3.6.1.4.1.34592.1.3.3.14.1}

#interface counters
#- {name: ont.counters.inPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.5 }
#- {name: ont.counters.outPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.27 }
- {name: ont.counters.inOctets, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.4}
- {name: ont.counters.outOctets, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.26}
- {name: ont.counters.inMulticastPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.7}
- {name: ont.counters.outMulticastPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.29}
- {name: ont.counters.inCrcErrors, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.22}
- {name: ont.counters.outCrcErrors, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.44}
#- {name: ont.counters.inBroadcastPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.6}
#- {name: ont.counters.outBroadcastPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.28}
- {name: ont.counters.InDiscards, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.23 }
- {name: ont.counters.OutDiscards, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.45 }
#- {name: ont.counters.statInUndersizePkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.15 }
#- {name: ont.counters.statOutUndersizePkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.37 }
#- {name: ont.counters.statInJabberPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.24 }
#- {name: ont.counters.statOutJabber, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.46 }
#- {name: ont.counters.statInOversizePkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.16 }
#- {name: ont.counters.statOutOversizePkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.38 }
#- {name: ont.counters.statInFragmentsPkts, oid: 1.3.6.1.4.1.17409.2.3.10.1.1.17}
#- {name: ont.counters.statOutFragmentsPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.39 }

#UNI Block
- {name: ont.uni.opStatus, oid: .1.3.6.1.4.1.17409.2.3.5.1.1.5, values: {1: Up, 2: Down}}
- {name: ont.uni.adminState, oid:  .1.3.6.1.4.1.17409.2.3.5.1.1.4, values: {1: Enabled, 2: Disabled}}
- {name: ont.uni.vlanId, oid: .1.3.6.1.4.1.17409.2.3.7.3.1.1.7 }
- {name: ont.uni.vlanMode, oid: .1.3.6.1.4.1.17409.2.3.7.3.1.1.8, values: {0: Unknown, 1: Untagged, 2: Tagged }}

