
- {name: resources.cpuUsage, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.1}
- {name: resources.memTotalSize, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.2}
- {name: resources.memFreeSize, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.3}
- {name: resources.temperature, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.6} # val / 100
- {name: resources.temperatureTreshhold, oid: .1.3.6.1.4.1.34592.1.3.100.1.8.7}


- {name: sys.macAddr, oid: .1.3.6.1.4.1.17409.2.3.1.1.6}
- {name: sys.vendorName, oid: .1.3.6.1.4.1.17409.2.3.1.1.12}
- {name: sys.serialNum, oid: .1.3.6.1.4.1.17409.2.3.1.1.13}
- {name: sys.boardHardwareVer, oid: .1.3.6.1.4.1.17409.2.3.1.3.1.1.7.1}
- {name: sys.boardSoftwareVer, oid: .1.3.6.1.4.1.17409.2.3.1.3.1.1.9.1}
- {name: vlan.list, oid: .1.3.6.1.4.1.17409.2.3.7.2.1.1.3}
- {name: vlan.tagged, oid: .1.3.6.1.4.1.17409.2.3.7.2.1.1.4}
- {name: vlan.untagged, oid: .1.3.6.1.4.1.17409.2.3.7.2.1.1.5}

- {name: sys.dbaProfileNames, oid: .1.3.6.1.4.1.17409.2.8.11.1.1.1.2}
- {name: sys.lineProfileNames, oid: .1.3.6.1.4.1.17409.2.8.11.2.1.1.2}
- {name: sys.srvProfileNames, oid: .1.3.6.1.4.1.17409.2.8.11.3.1.1.2}

- {name: snoop.dhcpBindMacAddr, oid: .1.3.6.1.4.1.34592.1.3.100.5.4.1.3}
- {name: snoop.dhcpBindPortId, oid: .1.3.6.1.4.1.34592.1.3.100.5.4.1.4}
- {name: snoop.dhcpBindType, oid: .1.3.6.1.4.1.34592.1.3.100.5.4.1.5}

#FDB INFO

#В конце указано .2.1.0, где 1 - олт, 0 - карта
#Так как в стекируемых нет необходимости - добавлен 1.0
- {name: pon.fdbWithUni, oid: .1.3.6.1.4.1.34592.1.5.1.1.2.19.3.1.2.1.0}

# PON PORT BLOCK
  # OpTemp ..1.3.6.1.4.1.34592.1.3.100.2.2.1.4.1.0.9
  # where 1.0.9
  # 1 - device index (default=1)
  # 0 - card number (default=1)
  # 9 - number of port (stored in xid value in model extra parameters)
- {name: ont.description, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.2}
- {name: pon.portOperStatus, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.5, values: {1: Up, 2: Down, 3: Testing}}
- {name: pon.portAdminStatus, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.6, values: {1: Enabled, 2: Disabled}} #SNMPSET
- {name: pon.portMaxOnuNumSupport, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.7}
- {name: pon.portMaxDsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.12}
- {name: pon.portActualDsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.13}
- {name: pon.portRemainDsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.14}
- {name: pon.portMaxUsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.18}
- {name: pon.portActualUsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.19}
- {name: pon.portRemainUsBandwidth, oid: .1.3.6.1.4.1.17409.2.3.3.1.1.20}
- {name: pon.portOpticalRxOfOnu, oid: .1.3.6.1.4.1.17409.2.3.3.6.1.2}

#SNMP ACTIONS
- {name: ont.action.reboot, oid: .1.3.6.1.4.1.17409.2.3.5.1.1.8, values: {1: Action}}
- {name: olt.save, oid: .1.3.6.1.4.1.17409.2.3.1.1.14.0, values: {1: Action}}
- {name: ont.action.delete, oid: .1.3.6.1.4.1.17409.2.3.4.5.2.1.4, values: {6: Delete}}
- {name: ont.action.resetOnu, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.10, values: {1: Reset}}
- {name: ont.action.clear_counters, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.48}

#ONT BLOCK
- {name: ont.opticalRx, oid: .1.3.6.1.4.1.17409.2.8.4.4.1.4}
- {name: ont.opticalTx, oid: .1.3.6.1.4.1.17409.2.8.4.4.1.5}
- {name: ont.opticalVoltage, oid: .1.3.6.1.4.1.17409.2.8.4.4.1.7}
- {name: ont.opticalTemp, oid: .1.3.6.1.4.1.17409.2.8.4.4.1.8}
- {name: ont.serialNum, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.3}
- {name: ont.distance, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.9}
- {name: ont.deactive, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.11, values: {1: Active, 2: Deactive}}
- {name: ont.name, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.2}
- {name: ont.opStatus, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.7, values: {1: Up, 2: Down}}
- {name: ont.adminStatus, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.8, values: {1: Enabled, 2: Disabled}}
- {name: ont.verSoftware, oid: .1.3.6.1.4.1.17409.2.3.4.1.1.13}
- {name: ont.verHardware, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.14}
- {name: ont.vendor, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.5}
- {name: ont.model, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.6}
- {name: ont.lastRegSince, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.12}
- {name: ont.sysUptime, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.13}
- {name: ont.lastDownReason, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.103, values: {'--': Unknown, 'dying-gasp': Dying Gasp, 'LOS': Losi, 'losi': Losi, '': Unknown}}
- {name: ont.lastDownSince, oid: .1.3.6.1.4.1.17409.2.8.4.1.1.102}
- {name: pon.ontStatus, oid: .1.3.6.1.4.1.34592.1.3.3.14.1}

#UNI Block
- {name: ont.uni.opStatus, oid: .1.3.6.1.4.1.17409.2.8.5.1.1.5, values: {1: Up, 2: Down}}
- {name: ont.uni.adminStatus, oid:  .1.3.6.1.4.1.17409.2.8.5.1.1.4, values: {1: Enabled, 2: Disabled}}
#- {name: ont.uni.statInOctets, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.4 }
#- {name: ont.uni.statInUndersizePkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.15 }
#- {name: ont.uni.statInOversizePkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.16 }
#- {name: ont.uni.statInFragmentsPkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.17}
#- {name: ont.uni.statInCrcPkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.22 }
#- {name: ont.uni.statInDropPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.23 }
#- {name: ont.uni.statInJabberPkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.24 }
#- {name: ont.uni.statOutOctets, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.26 }
#- {name: ont.uni.statOutUndersizePkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.37 }
#- {name: ont.uni.statOutOversizePkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.38 }
#- {name: ont.uni.statOutFragmentsPkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.39 }
#- {name: ont.uni.statOutCrcPkts, oid: .1.3.6.1.4.1.17409.2.3.10.1.1.44 }
#- {name: ont.uni.statOutDropPkts, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.45 }
#- {name: ont.uni.statOutJabber, oid:  .1.3.6.1.4.1.17409.2.3.10.1.1.46 }
