#SYSTEM OIDS
  - {name: sys.Descr, oid: .1.3.6.1.2.1.1.1, access: read }
  - {name: sys.ObjId, oid: .1.3.6.1.2.1.1.2, access: read }
  - {name: sys.Uptime, oid: .1.3.6.1.2.1.1.3, access: read }
  - {name: sys.Contact, oid: .1.3.6.1.2.1.1.4, access: write, type: string }
  - {name: sys.Name, oid: .1.3.6.1.2.1.1.5, access: write, type: string }
  - {name: sys.Location, oid: .1.3.6.1.2.1.1.6, access: write, type: string }

# Not all device supported
#  - {name: sys.Revision, oid: .1.3.6.1.2.1.47.1.1.1.1.8.1, type: string }
#  - {name: sys.Firmware, oid: .1.3.6.1.2.1.47.1.1.1.1.9.1, type: string }
#if mib (.iso.org.dod.internet.mgmt.mib-2.interfaces + .iso.org.dod.internet.mgmt.mib-2.ifMIB.ifMIBObjects.ifXTable.ifXEntry)
  - {name: if.Number, oid: .1.3.6.1.2.1.2.1, access: read }
  - {name: if.Index, oid: .1.3.6.1.2.1.2.2.1.1, access: read }
  - {name: if.Descr, oid: .1.3.6.1.2.1.2.2.1.2, access: read }
  - {name: if.Type, oid: .1.3.6.1.2.1.2.2.1.3, access: read, values: {6: FE, 117: GE, 135: VLAN, 136: VLAN, 137: VLAN, 207: PON, 208: PON, 250: GPON, 266: ONU, 142: IP, 300: EPON}}
  - {name: if.StatsDuplexStatus, oid: .1.3.6.1.2.1.10.7.2.1.19, access: read , values: {1: Down, 2: Half, 3: Full}}
  #Включен/отключен интерфейс
  # 1-UP/2-DOWN/3-TESTING
  - {name: if.AdminStatus, oid: .1.3.6.1.2.1.2.2.1.7, access: write, type: integer, values: {1: Enabled, 2: Disabled, 3: TESTING} }
  #Текущее состояние интерфейса
  # 1-UP/2-DOWN/6-NOT PRESENT
  - {name: if.OperStatus, oid: .1.3.6.1.2.1.2.2.1.8, access: read, values: {1: Up, 2: Down, 6: NOT_PRESENT} }
  #The value of sysUpTime at the time the interface entered its current operational state.  If the current state was entered prior to the last re-initialization of the local network management subsystem, then this object contains a zero value.
  - {name: if.LastChange, oid: .1.3.6.1.2.1.2.2.1.9, access: read }
  - {name: if.InErrors, oid: .1.3.6.1.2.1.2.2.1.14, access: read }
  - {name: if.OutErrors, oid: .1.3.6.1.2.1.2.2.1.20, access: read }
  - {name: if.InDiscards, oid: .1.3.6.1.2.1.2.2.1.13, access: read }
  - {name: if.OutDiscards, oid: .1.3.6.1.2.1.2.2.1.19, access: read }
  - {name: if.HCInOctets, oid: .1.3.6.1.2.1.31.1.1.1.6, access: read }
  - {name: if.HCOutOctets, oid: .1.3.6.1.2.1.31.1.1.1.10, access: read }
  - {name: if.HCOutMulticastPkts, oid: .1.3.6.1.2.1.31.1.1.1.12, access: read }
  - {name: if.HCInMulticastPkts, oid: .1.3.6.1.2.1.31.1.1.1.8, access: read }
  - {name: if.HCOutBroadcastPkts, oid: .1.3.6.1.2.1.31.1.1.1.13, access: read }
  - {name: if.HCInBroadcastPkts, oid: .1.3.6.1.2.1.31.1.1.1.9, access: read }

  - {name: if.HighSpeed, oid: .1.3.6.1.2.1.31.1.1.1.15, access: read, values: {1000: 1G} }
  - {name: if.ConnectorPresent, oid: .1.3.6.1.2.1.31.1.1.1.17, access: read, values: { 1: 'YES', 2: 'NO' } }
  - {name: if.Name, oid: .1.3.6.1.2.1.31.1.1.1.1, access: read }
  - {name: if.Alias, oid: .1.3.6.1.2.1.31.1.1.1.18, access: read }
#rmon mib
  - {name: rmon.EtherStatsCRCAlignErrors, oid: .1.3.6.1.2.1.16.1.1.1.8, access: read }
  - {name: rmon.EtherStatsUndersizePkts, oid: .1.3.6.1.2.1.16.1.1.1.9, access: read }
  - {name: rmon.EtherStatsOversizePkts, oid: .1.3.6.1.2.1.16.1.1.1.10, access: read }
  - {name: rmon.EtherStatsFragments, oid: .1.3.6.1.2.1.16.1.1.1.11, access: read }
  - {name: rmon.EtherStatsJabber, oid: .1.3.6.1.2.1.16.1.1.1.12, access: read }
  - {name: rmon.EtherStatsCollisions, oid: .1.3.6.1.2.1.16.1.1.1.13, access: read }
  - {name: rmon.EtherStatsDropEvents, oid: .1.3.6.1.2.1.16.1.1.1.3, access: read }
#qBridgeMIB - dot1qVlan
  - {name: dot1q.VlanStaticName, oid: .1.3.6.1.2.1.17.7.1.4.3.1.1, access: read}
  - {name: dot1q.VlanStaticEgressPorts, oid: .1.3.6.1.2.1.17.7.1.4.3.1.2, access: read} #RETURNED HEX-STRING, must wrapped to binary. num of byte = num port; 1 = on port
  - {name: dot1q.VlanStaticForbiddenEgressPorts, oid: .1.3.6.1.2.1.17.7.1.4.3.1.3, access: read} #RETURNED HEX-STRING, must wrapped to binary. num of byte = num port; 1 = on port
  - {name: dot1q.VlanStaticUntaggedPorts, oid: .1.3.6.1.2.1.17.7.1.4.3.1.4, access: read } #RETURNED HEX-STRING, must wrapped to binary. num of byte = num port; 1 = on port
  - {name: dot1q.VlanStaticRowStatus, oid: .1.3.6.1.2.1.17.7.1.4.3.1.5, access: read } #RETURNED HEX-STRING, must wrapped to binary. num of byte = num port; 1 = on port
#qBridgeMIB - dot1qBase
  - {name: dot1q.Pvid, oid: .1.3.6.1.2.1.17.7.1.4.5.1.1, access: read}
  - {name: dot1q.NumVlans, oid: .1.3.6.1.2.1.17.7.1.1.4, access: read}
  - {name: dot1q.MaxVlanId, oid: .1.3.6.1.2.1.17.7.1.1.1, access: read}
  - {name: dot1q.MaxSupportedVlans, oid: .1.3.6.1.2.1.17.7.1.1.3, access: read}
#qBridgeMIB - dot1qTp
# .1.3.6.1.2.1.17.7.1.2.2.1.2.[VLAN ID].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET] = [PORT]
  - {name: dot1q.FdbPort, oid: .1.3.6.1.2.1.17.7.1.2.2.1.2, access: read}
# .1.3.6.1.2.1.17.7.1.2.2.1.3.[VLAN ID].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET].[MAC-OCTET] = [STATUS]
  - {name: dot1q.FdbStatus, oid: .1.3.6.1.2.1.17.7.1.2.2.1.3, access: read, values: {1: OTHER, 2: INVALID, 3: LEARNED, 4: SELF, 5: MGMT}}
