- {name: hrDevice.hrProcessorLoad, oid: .1.3.6.1.2.1.25.3.3.1.2.1 } # CPU Load in %
- {name: resources.temperature.cpu, oid: .1.3.6.1.2.1.99.1.1.1.4.100006001 } # CPU Temp Sensor in Celsius, need to be divide by 10 (Arista Networks EOS version 4.29.8M on Arista Networks DCS-7060SX2-48YC6)


### Free memory = (Total RAM – Used RAM) + Buffers + Cache  ( https://arista.my.site.com/AristaCommunity/s/article/memory-utilization-on-eos-devices#Comm_Kna_ka08C0000008SHcQAM_45 )
- {name: hrStorage.hrStorageSize, oid: .1.3.6.1.2.1.25.2.3.1.5.1 } # Total RAM
- {name: hrStorage.hrStorageUsed.Total, oid: .1.3.6.1.2.1.25.2.3.1.6.1 } # Used Memory
- {name: hrStorage.hrStorageUsed.Buffers, oid: .1.3.6.1.2.1.25.2.3.1.6.2 } # Buffers
- {name: hrStorage.hrStorageUsed.Cache, oid: .1.3.6.1.2.1.25.2.3.1.6.3 } # Cache
- {name: hrStorage.hrStorageUsed.MemoryInUse, oid: .1.3.6.1.2.1.25.2.3.1.6.100 } # in an enhancement from EOS version 4.22.0F and onwards HOST-RESOURCES-MIB::hrStorageTable[100] is an SNMP MIB to track ‘memory in use’ that is not buffers or cache. Hence, the output of hrStorageUsed[100] can be used to get a more accurate estimate of the memory that is getting used.

