<?php


namespace SwitcherCore\Modules\VsolOlts\GPONV1600;


use Exception;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Modules\Helper;
use SwitcherCore\Switcher\Objects\SnmpResponse;

class InterfaceDescriptions extends VsolOltsAbstractModule
{
    /**
     * @var SnmpResponse[]
     */
    protected $response = null;

    function getRaw()
    {
        return $this->response;
    }

    function getPrettyFiltered($filter = [], $fromCache = false)
    {
        return parent::getPrettyFiltered($filter, $fromCache); // TODO: Change the autogenerated stub
    }

    function getPretty()
    {
        $data = [];
        foreach ($this->response as $oidName => $dt) {
            foreach ($dt as $resp) {
                $id = Helper::getIndexByOid($resp->getOid());
                if ($oidName == 'ont.description') {
                    $id = ".". Helper::getIndexByOid($resp->getOid(), 1) . "." .Helper::getIndexByOid($resp->getOid());
                }
                $interface = $this->parseInterface($id);
                $data[] = [
                    'interface' => $interface,
                    'description' => $this->convertHexToString($resp->getHexValue()),
                ];
            }
        }
        return $data;
    }

    public function fetchData($data, $oid_name = 'ont.description')
    {
        $resp = $this->getResponseByName($oid_name, $data);
        if ($resp->error()) {
            throw new \Exception($resp->error());
        }
        return $this->getResponseByName($oid_name, $data)->fetchAll();
    }

    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        if ($filter['interface']) {
            $interface = $this->parseInterface($filter['interface']);
            if ($interface['type'] == 'ONU') {
                $oid_name = 'ont.description';
                $data = $this->formatResponse(
                    $this->snmp->get([\SnmpWrapper\Oid::init($this->oids->getOidByName($oid_name)->getOid() . "{$interface['_snmp_id']}"),])
                );
                $this->response[$oid_name] = $this->fetchData($data);
            } else {
                $oid_name = 'if.Name';
                $data = $this->formatResponse(
                    $this->snmp->get([\SnmpWrapper\Oid::init($this->oids->getOidByName($oid_name)->getOid() . ".{$interface['xid']}"),])
                );
                $this->response[$oid_name] = $this->fetchData($data, $oid_name);
            }
            return $this;
        }

        $without_arguments = false;
        if (!isset($filter['interface_type'])) {
            $without_arguments = true;
        }

        if ($filter['interface_type'] == 'ONU' || $without_arguments) {
            $oid_name = 'ont.description';
            $data = $this->formatResponse(
                $this->snmp->walkNext([\SnmpWrapper\Oid::init($this->oids->getOidByName($oid_name)->getOid()),])
            );
            $this->response[$oid_name] = $this->fetchData($data);
        }
        if ($filter['interface_type'] == 'PHYSICAL' || $without_arguments) {
            $oid_name = 'if.Name';
            $data = $this->formatResponse(
                $this->snmp->walkNext([\SnmpWrapper\Oid::init($this->oids->getOidByName($oid_name)->getOid()),])
            );
            $this->response[$oid_name] = $this->fetchData($data, $oid_name);
        }

        return $this;
    }
}

