models:
- name: Arista
  key: arista_default
  device_type: SWITCH
  inputs:
    - snmp
    - console
  oids:
    - ./oids/arista/defaults.yml
  extra:
    console_conn_type: arista
  detect: {description: .*Arista.*,  objid: ^.1.3.6.1.4.1.30065.1.3011 }
  modules:
    parse_interface: \SwitcherCore\Modules\Arista\ParseInterface
    fdb: \SwitcherCore\Modules\Arista\Fdb
    link_info: \SwitcherCore\Modules\Arista\LinkInfo
    interface_counters: \SwitcherCore\Modules\Arista\Counters
    system: \SwitcherCore\Modules\Arista\System
    vlans: \SwitcherCore\Modules\Arista\VlansDot1q
    errors: \SwitcherCore\Modules\Arista\Errors
    rmon: \SwitcherCore\Modules\Arista\Rmon
    vlans_by_port: \SwitcherCore\Modules\Arista\VlanByPorts
    interface_descriptions: \SwitcherCore\Modules\Arista\Descriptions
    interfaces_list: \SwitcherCore\Modules\Arista\InterfacesList
    lldp_info: \SwitcherCore\Modules\Arista\LldpInfo
    net_settings: \SwitcherCore\Modules\Arista\NetSettings
    sys_resources: \SwitcherCore\Modules\Arista\SystemResources
    pvid: \SwitcherCore\Modules\Arista\PvidDot1q
    console_command: \SwitcherCore\Modules\Arista\RawConsoleCommand
    multi_console_command: \SwitcherCore\Modules\Arista\MultiRawConsoleCommand
    supported_modules: \SwitcherCore\Modules\General\SupportedModules