models:
  - name: BDCOM P3310C
    key: bdcom_p3310c
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3310C.*,  objid: ^.1.3.6.1.4.1.3320.1.294.0$}
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\OntOpticalInfo
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      pon_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      pon_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      pon_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_counters: \SwitcherCore\Modules\BDcom\UniInterfacesCounters
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
    extra:
      console_conn_type: bdcom
      console_commands_after_connect:
        - enable
        - terminal length 0
      interfaces:
        - {name: g0/1, id: 1, xid: 9, type: GE}
        - {name: g0/2, id: 2, xid: 10, type: GE}
        - {name: g0/3, id: 3, xid: 11, type: GE}
        - {name: g0/4, id: 4, xid: 12, type: GE}
        - {name: g0/5, id: 5, xid: 13, type: GE}
        - {name: g0/6, id: 6, xid: 14, type: GE}
        - {name: epon0/1, id: 10100000, xid: 15, type: PON, pontype: epon}
        - {name: epon0/2, id: 10200000, xid: 16, type: PON, pontype: epon}
        - {name: epon0/3, id: 10300000, xid: 17, type: PON, pontype: epon}
        - {name: epon0/4, id: 10400000, xid: 18, type: PON, pontype: epon}
