models:
  - name: BDCOM GP3600 series
    key: bdcom_gp3600_series
    inputs:
      - snmp
      - console
    detect: {description: .*GP3600,  objid: ^.1.3.6.1.4.1.3320 }
    device_type: OLT
    rewrites:
      oid: .1.3.6.1.4.1.3320.9.181.1.1.2.0
      mapping:
        - value: ^GP3600-04
          rewrite:
            key: bdcom_gp3600_04
            name: BDCOM GP3600-04
        - value: ^GP3600-08
          rewrite:
            key: bdcom_gp3600_08
            name: BDCOM GP3600-08
        - value: ^GP3600-16
          rewrite:
            key: bdcom_gp3600_16
            name: BDCOM GP3600-16
    oids:
      - ./oids/bdcom/gp3600.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\GP3600\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\GP3600\PortCountRegisteredOnts
      parse_interface: \SwitcherCore\Modules\BDcom\GP3600\ParseInterface
      pon_onts_status: \SwitcherCore\Modules\BDcom\GP3600\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\BDcom\GP3600\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\BDcom\GP3600\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\GP3600\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\GP3600\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\GP3600\OntVendorInfo
      vlans: \SwitcherCore\Modules\BDcom\GP3600\VlanList
      fdb: \SwitcherCore\Modules\BDcom\GP3600\FdbTableConsole
      interface_descriptions: \SwitcherCore\Modules\BDcom\GP3600\InterfaceDescriptions
      sys_resources: \SwitcherCore\Modules\BDcom\GP3600\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\GP3600\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\GP3600\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\GP3600\InterfacesList
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\GP3600\UniInterfacesStatus
      pon_profiles: \SwitcherCore\Modules\BDcom\GP3600\GponProfiles
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\GP3600\UniInterfacesVlans
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\GP3600\OntReboot
      ctrl_ont_disable: \SwitcherCore\Modules\BDcom\GP3600\CtrlOntDisable
      ctrl_ont_descr: \SwitcherCore\Modules\BDcom\GP3600\CtrlOntDescription
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\GP3600\OntDelete
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\GP3600\UniInterfacesControlAdminStatus
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      link_info: \SwitcherCore\Modules\BDcom\GP3600\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\GP3600\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\GP3600\UnregisteredOnts
    extra:
      pon_port_size: 128
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P3612-2TE
    key: bdcom_p3612_2te
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3612-2TE.*,  objid: ^.1.3.6.1.4.1.3320.1.2010.0 }
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\P3608B\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P3616-2TE
    key: bdcom_p3616_2te
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3616-2TE.*,  objid: .1.3.6.1.4.1.3320.1.2011.0 }
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\P3608B\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P3608B
    key: bdcom_p3608b
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3608B.*,  objid: ^.1.3.6.1.4.1.3320 }
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\P3608B\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P36xx series
    key: bdcom_p36xx_series
    inputs:
      - snmp
      - console
    detect: {description: '^BDCOM.*?P36.*' ,  objid: ^.1.3.6.1.4.1.3320 }
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\P3608B\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P3310C
    key: bdcom_p3310c
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3310C.*,  objid: ^.1.3.6.1.4.1.3320.1.294.0$}
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P3310D
    key: bdcom_p3310d
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3310D.*,  objid: ^.1.3.6.1.4.1.3320.1.441.0$}
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0

  - name: BDCOM P3310B
    key: bdcom_p3310b
    inputs:
      - snmp
      - console
    detect: {description: ^BDCOM.*P3310B.*,  objid: ^.1.3.6.1.4.1.3320.* }
    device_type: OLT
    oids:
      - ./oids/bdcom/3310c.yml
    traps:
      - ./traps/bdcom.yml
    modules:
      system: \SwitcherCore\Modules\BDcom\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\BDcom\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\BDcom\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\BDcom\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\BDcom\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\BDcom\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\BDcom\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\BDcom\P3310B\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\BDcom\P3310B\OntVendorInfo
      fdb: \SwitcherCore\Modules\BDcom\FdbTableConsole
      save_config: \SwitcherCore\Modules\BDcom\OltSaveSettings
      ctrl_ont_reboot: \SwitcherCore\Modules\BDcom\OntReboot
      ctrl_ont_reset: \SwitcherCore\Modules\BDcom\OntReset
      ctrl_ont_delete: \SwitcherCore\Modules\BDcom\OntDelete
      parse_interface: \SwitcherCore\Modules\BDcom\ParseInterface
      sys_resources: \SwitcherCore\Modules\BDcom\SystemResources
      #interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCounters
      interface_counters: \SwitcherCore\Modules\BDcom\InterfaceCountersNew
      interfaces_list: \SwitcherCore\Modules\BDcom\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\BDcom\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\BDcom\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\BDcom\UniInterfacesVlans
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\BDcom\UniInterfacesControlAdminStatus
      link_info: \SwitcherCore\Modules\BDcom\LinkInfo
      console_command: \SwitcherCore\Modules\BDcom\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\BDcom\MultiRawConsoleCommand
      ctrl_port_descr: \SwitcherCore\Modules\BDcom\PortDescriptionControl
      unregistered_onts: \SwitcherCore\Modules\BDcom\UnregisteredOnts
    extra:
      pon_port_size: 64
      console_conn_type: bdcom
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - terminal length 0