models:
  - name: C-Data FD1204SN
    key: c_data_fd1204sn
    inputs:
      - snmp
    detect: {description: EasyPath Ethernet-PON,  objid: ^.1.3.6.1.4.1.17409$, ifacesCount: 10}
    device_type: OLT
    oids:
      - ./oids/cdata/fd-epon-series.yml
    modules:
      system: \SwitcherCore\Modules\CData\SystemInformation
      vlans: \SwitcherCore\Modules\CData\Vlans
      pon_interfaces_list: \SwitcherCore\Modules\CData\InterfacesList
      pon_count_registered_onts: \SwitcherCore\Modules\CData\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\CData\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\CData\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\CData\OntOpticalInfo
      pon_onts_status_detailed: \SwitcherCore\Modules\CData\OntStatusDetailedInfo
      pon_onts_general_info: \SwitcherCore\Modules\CData\OntGeneralInfo
      pon_fdb: \SwitcherCore\Modules\CData\OntFDBTable
      pon_interface_info: \SwitcherCore\Modules\CData\OntUniInterfaceInformation
      pon_interfaces_tree: \SwitcherCore\Modules\CData\PonInterfacesTree
      save_config: \SwitcherCore\Modules\CData\OltSaveSettings
      pon_ont_reboot: \SwitcherCore\Modules\CData\OntReboot
      pon_ont_reset: \SwitcherCore\Modules\CData\OntReset
      pon_ont_delete: \SwitcherCore\Modules\CData\OntDelete
      pon_ont_clear_counters: \SwitcherCore\Modules\CData\OntUniClearCounters
      parse_interface: \SwitcherCore\Modules\CData\ParseInterface
    extra:
      interfaces:
        - {name: ge0/0/1, id: 16777472,  xid: 1, type: 1G-SFP}
        - {name: ge0/0/2, id: 16777728,  xid: 2, type: 1G-SFP}
        - {name: ge0/0/3, id: 16777984,  xid: 3, type: 1G-SFP}
        - {name: ge0/0/4, id: 16778240,  xid: 4, type: 1G-SFP}
        - {name: xge0/0/1, id: 16778240,  xid: 5, type: 10G-SFP}
        - {name: xge0/0/2, id: 16778752,  xid: 6, type: 10G-SFP}
        - {name: pon0/0/1, id: 16779008,  xid: 7, type: PON, pontype: epon}
        - {name: pon0/0/2, id: 16779264,  xid: 8, type: PON, pontype: epon}
        - {name: pon0/0/3, id: 16779520,  xid: 9, type: PON, pontype: epon}
        - {name: pon0/0/4, id: 16779776,  xid: 10, type: PON, pontype: epon}

  - name: C-Data FD1208S
    key: c_data_fd1208s
    inputs:
      - snmp
      - telnet
    detect: {description: EasyPath Ethernet-PON,  objid: ^.1.3.6.1.4.1.17409$, ifacesCount: 20}
    device_type: OLT
    oids:
      - ./oids/cdata/fd-epon-series.yml
      - ./oids/cdata/fd-1208s-r1.yml
    modules:
      system: \SwitcherCore\Modules\CData\SystemInformation
      vlans: \SwitcherCore\Modules\CData\Vlans
      pon_interfaces_list: \SwitcherCore\Modules\CData\InterfacesList
      pon_count_registered_onts: \SwitcherCore\Modules\CData\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\CData\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\CData\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\CData\OntOpticalInfo
      pon_onts_status_detailed: \SwitcherCore\Modules\CData\OntStatusDetailedInfo
      pon_onts_general_info: \SwitcherCore\Modules\CData\OntGeneralInfo
      pon_fdb: \SwitcherCore\Modules\CData\FdbTableTelnet
      pon_interface_info: \SwitcherCore\Modules\CData\OntUniInterfaceInformation
      pon_interfaces_tree: \SwitcherCore\Modules\CData\PonInterfacesTree
      save_config: \SwitcherCore\Modules\CData\OltSaveSettings
      pon_ont_reboot: \SwitcherCore\Modules\CData\OntReboot
      pon_ont_reset: \SwitcherCore\Modules\CData\OntReset
      pon_ont_delete: \SwitcherCore\Modules\CData\OntDelete
      pon_ont_clear_counters: \SwitcherCore\Modules\CData\OntUniClearCounters
      parse_interface: \SwitcherCore\Modules\CData\ParseInterface
    extra:
      telnet_conn_type: cdata
      interfaces:
        - {name: ge0/0/1, id: 16777472,  xid: 1, type: 1G-SFP}
        - {name: ge0/0/2, id: 16777728,  xid: 2, type: 1G-SFP}
        - {name: ge0/0/3, id: 16777984,  xid: 3, type: 1G-SFP}
        - {name: ge0/0/4, id: 16778240,  xid: 4, type: 1G-SFP}
        - {name: ge0/0/5, id: 16778496,  xid: 5, type: 1G-SFP}
        - {name: ge0/0/6, id: 16778752,  xid: 6, type: 1G-SFP}
        - {name: ge0/0/7, id: 16779008,  xid: 7, type: 1G-SFP}
        - {name: ge0/0/8, id: 16779264,  xid: 8, type: 1G-SFP}
        - {name: xge0/0/1, id: 16779520,  xid: 9, type: 10G-SFP}
        - {name: xge0/0/2, id: 16779776,  xid: 10, type: 10G-SFP}
        - {name: xge0/0/3, id: 16780032,  xid: 11, type: 10G-SFP}
        - {name: xge0/0/4, id: 16780288,  xid: 12, type: 10G-SFP}
        - {name: pon0/0/1, id: 16780544,  xid: 13, type: PON, pontype: epon}
        - {name: pon0/0/2, id: 16780800,  xid: 14, type: PON, pontype: epon}
        - {name: pon0/0/3, id: 16781056,  xid: 15, type: PON, pontype: epon}
        - {name: pon0/0/4, id: 16781312,  xid: 16, type: PON, pontype: epon}
        - {name: pon0/0/5, id: 16781568,  xid: 17, type: PON, pontype: epon}
        - {name: pon0/0/6, id: 16781824,  xid: 18, type: PON, pontype: epon}
        - {name: pon0/0/7, id: 16782080,  xid: 19, type: PON, pontype: epon}
        - {name: pon0/0/8, id: 16782336,  xid: 20, type: PON, pontype: epon}

  - name: C-Data FD1616SN-R1
    key: c_data_fd1616sn_r1
    inputs:
      - snmp
    detect: {description: ^FD1616SN-R1$,  objid: ^.1.3.6.1.4.1.17409$}
    device_type: OLT
    oids:
      - ./oids/cdata/fd-gpon-series.yml
    modules:
      system: \SwitcherCore\Modules\CData\SystemInformation
      vlans: \SwitcherCore\Modules\CData\Vlans
      pon_interfaces_list: \SwitcherCore\Modules\CData\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\CData\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\CData\GponOntSerial
      pon_onts_optical: \SwitcherCore\Modules\CData\OntOpticalInfo
      pon_onts_status_detailed: \SwitcherCore\Modules\CData\OntStatusDetailedInfo
      pon_onts_general_info: \SwitcherCore\Modules\CData\OntGeneralInfo
      pon_fdb: \SwitcherCore\Modules\CData\GponOntFdbTable
      pon_interface_info: \SwitcherCore\Modules\CData\OntUniInterfaceInformation
      pon_interfaces_tree: \SwitcherCore\Modules\CData\PonInterfacesTree
      save_config: \SwitcherCore\Modules\CData\OltSaveSettings
      #pon_ont_reboot: \SwitcherCore\Modules\CData\OntReboot
      #pon_ont_reset: \SwitcherCore\Modules\CData\OntReset
      #pon_ont_delete: \SwitcherCore\Modules\CData\OntDelete
      #pon_ont_clear_counters: \SwitcherCore\Modules\CData\OntUniClearCounters
      parse_interface: \SwitcherCore\Modules\CData\ParseInterface
    extra:
      interfaces:
        - {name: ge0/0/1, id: 16777472,  xid: 1, type: 1G-SFP}
        - {name: ge0/0/2, id: 16777728,  xid: 2, type: 1G-SFP}
        - {name: ge0/0/3, id: 16777984,  xid: 3, type: 1G-SFP}
        - {name: ge0/0/4, id: 16778240,  xid: 4, type: 1G-SFP}
        - {name: xge0/0/1, id: 16778496,  xid: 5, type: 10G-SFP}
        - {name: xge0/0/2, id: 16778752,  xid: 6, type: 10G-SFP}
        - {name: pon0/0/1, id: 16779008,  xid: 7, type: PON, pontype: gpon}
        - {name: pon0/0/2, id: 16779264,  xid: 8, type: PON, pontype: gpon}
        - {name: pon0/0/3, id: 16779520,  xid: 9, type: PON, pontype: gpon}
        - {name: pon0/0/4, id: 16779776,  xid: 10, type: PON, pontype: gpon}
        - {name: pon0/0/5, id: 16780032,  xid: 11, type: PON, pontype: gpon}
        - {name: pon0/0/6, id: 16780288,  xid: 12, type: PON, pontype: gpon}
        - {name: pon0/0/7, id: 16780544,  xid: 13, type: PON, pontype: gpon}
        - {name: pon0/0/8, id: 16780800,  xid: 14, type: PON, pontype: gpon}
        - {name: pon0/0/9, id: 16781056,  xid: 15, type: PON, pontype: gpon}
        - {name: pon0/0/10, id: 16781312,  xid: 16, type: PON, pontype: gpon}
        - {name: pon0/0/11, id: 16781568,  xid: 17, type: PON, pontype: gpon}
        - {name: pon0/0/12, id: 16781824,  xid: 18, type: PON, pontype: gpon}
        - {name: pon0/0/13, id: 16782080,  xid: 19, type: PON, pontype: gpon}
        - {name: pon0/0/14, id: 16782336,  xid: 20, type: PON, pontype: gpon}
        - {name: pon0/0/15, id: 16782592,  xid: 21, type: PON, pontype: gpon}
        - {name: pon0/0/16, id: 16782848,  xid: 22, type: PON, pontype: gpon}
