############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################
models:
 - name: D-link DES-1210-28/ME/B2
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-1210-28-me-b2.yml
   detect: {description: ^DES-1210-28\/ME\/B2$,  objid: ^.*171.10.75.15.2$ }
   extra:
     ge_ports: [25,26,27,28]
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDgs1210Parser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl

