############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################

models:
 - name: D-link DES-3526
   ports: 26
   key: d_link_des_3526
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
    - ./oids/dlink/des-3526.yml
    - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^DES-3526 Fast-Ethernet Switch$,  objid: 171\.10\.64\.1$ }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDes3526Parser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\Des3526Parser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl
