############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################
models:
 - name: D-link DES-3200-10/A1
   ports: 10
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-10-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-10,  objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.1\.1 }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-10/C1
   ports: 10
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-10-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-10\/C1,  objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.2\.1 }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-18/C1
   ports: 18
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-18-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-18\/C1 Fast Ethernet Switch$,  objid: ^.*113\.3\.1$ }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-26/C1
   ports: 26
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-26-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-26\/C1 Fast Ethernet Switch$,  objid: ^.*113\.4\.1$ }
   extra:
     diag_linkup: false
     ge_ports: [25,26]
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-28/C1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-28-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-28\/C1 Fast Ethernet Switch$,  objid: ^.*113\.5\.1$ }
   extra:
     diag_linkup: false
     ge_ports: [25,26,27,28]
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-28F/C1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-28F-c1.yml
     - ./oids/dlink/des-3200-c1-diag.yml
   detect: {description: ^DES-3200-28F\/C1 Fast Ethernet Switch$,  objid: ^.*113\.6\.1$ }
   extra:
     diag_linkup: false
     ge_ports: [25,26,27,28]
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-18/A1
   ports: 18
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-18-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-18 Fast Ethernet Switch$,  objid: ^\.1\.3\.6\.1\.4\.1\.171\.10\.113\.1\.2 }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-26/A1
   ports: 26
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-26-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-26 Fast Ethernet Switch$,  objid: ^.*113.1.5$ }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-28/A1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-28-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-28 Fast Ethernet Switch$,  objid: ^.*113.1.3$ }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl


 - name: D-link DES-3200-28F/A1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - telnet
   oids:
     - ./oids/dlink/des-3200-28F-a1.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^D-Link DES-3200-28F Fast Ethernet Switch$,  objid: ^.*113.1.4$ }
   extra:
     diag_linkup: false
     telnet_conn_type: dlink
   modules:
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Telnet\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Telnet\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Telnet\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Telnet\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Telnet\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Telnet\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Telnet\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Telnet\Dlink\VlanPortControl

