############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################

models:
 - name: D-link DGS-1100-06/ME/A1
   key: dlink_dgs_1100_06_me_a1
   ports: 6
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-1100-06-me-a1.yml
   detect: {description: ^DGS-1100-06\/ME\/A1$,  objid: ^.*.171.10.134.1$ }
   extra:
     diag_linkup: true
     non_diag_ports: [6]
     ge_ports: [1,2,3,4,5,6]
     console_conn_type: dlink
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDgs1100Parser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkDgs1100Parser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCountersDGS1100
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\DGS1100SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand

 - name: D-link DGS-1100-10/ME
   key: dlink_dgs_1100_10_me_a1
   ports: 10
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-1100-10-me.yml
   detect: {description: ^DGS-1100-10\/ME,  objid: ^.*.171.10.134.2.1$ }
   extra:
     diag_linkup: false
     non_diag_ports: [9,10]
     ge_ports: [1,2,3,4,5,6,7,8,9,10]
     console_conn_type: dlink
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDgs1100Parser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkDgs1100Parser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCountersDGS1100
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\DGS1100SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand