############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################

models:
 - name: D-link DGS-3100-24TG
   key: dlink_dgs_3100_24tg
   ports: 24
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-3100-24tg.yml
   detect: {description: DGS-3100-24TG,  objid: .1.3.6.1.4.1.171.10.94.5 }
   extra:
     console_conn_type: dlink
     diag_linkup: false
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDGS3100
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DGS3100
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
    # cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\DGS3100SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
