############################################## Parameters description  #####################################################
## extra.ge_ports setted only if device response in cableDiag, link isn't correct. GE ports must detect automaticaly      ##
## extra.diag_ports used in cableDiag for diag only cooper ports. Cooper ports not choose automaticaly in diagnostic.
## extra.diag_linkup if setted false, links with operstatus=UP will be ignored, if port are not setted
##
##
############################################################################################################################

models:
 - name: D-link DGS-3000-10TC
   key: dlink_dgs_3000_10tc
   ports: 10
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/common-diag-cable.yml
     - ./oids/dlink/common-agent-info.yml
     - ./oids/dlink/dgs-3000-10tc.yml
   detect: {description: ^DGS-3000-10TC Gigabit Ethernet Switch$,  objid: .* }
   extra:
     console_conn_type: dlink
     diag_linkup: true
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand
     lldp_info: \SwitcherCore\Modules\Dlink\LldpInfo
     net_settings: \SwitcherCore\Modules\Dlink\NetSettings
 - name: D-link DGS-3000-26TC
   key: dlink_dgs_3000_26tc_a1
   ports: 26
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-3000-26tc.yml
     - ./oids/dlink/common-diag-cable.yml
     - ./oids/dlink/common-agent-info.yml
   detect: {description: ^DGS-3000-26TC Gigabit Ethernet Switch$,  objid: .* }
   extra:
     console_conn_type: dlink
     diag_linkup: true
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand
     lldp_info: \SwitcherCore\Modules\Dlink\LldpInfo
     net_settings: \SwitcherCore\Modules\Dlink\NetSettings

 - name: D-link DGS-3000-28L
   key: dlink_dgs_3000_28l_b1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-3000-28l.yml
     - ./oids/dlink/common-diag-cable.yml
     - ./oids/dlink/common-agent-info.yml
   detect: {description: ^DGS-3000-28L Gigabit Ethernet Switch$,  objid: .* }
   extra:
     console_conn_type: dlink
     diag_linkup: true
     ge_ports: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkParser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand
     lldp_info: \SwitcherCore\Modules\Dlink\LldpInfo
     net_settings: \SwitcherCore\Modules\Dlink\NetSettings