models:
 - name: D-link DGS-3420-28SC
   key: dlink_dgs_3420_28sc_b1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-3420-28sc-b1.yml
     - ./oids/dlink/common-agent-info.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^DGS-3420-28SC.*,  objid: .1.3.6.1.4.1.171.10.119.2 }
   extra:
     console_conn_type: dlink
     diag_linkup: true
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDgs3420Parser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand
     lldp_info: \SwitcherCore\Modules\Dlink\LldpInfo
     net_settings: \SwitcherCore\Modules\General\NetSettings
     supported_modules: \SwitcherCore\Modules\General\SupportedModules
     sys_temp: \SwitcherCore\Modules\General\SystemTemperatures
     sfp_optical: \SwitcherCore\Modules\Dlink\SfpDiag\SfpOpticalParser
 - name: D-link DGS-3420-26SC
   key: dlink_dgs_3420_26sc_b1
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
     - console
   oids:
     - ./oids/dlink/dgs-3420-26sc-b1.yml
     - ./oids/dlink/common-agent-info.yml
     - ./oids/dlink/common-diag-cable.yml
   detect: {description: ^DGS-3420-26SC.*,  objid: .1.3.6.1.4.1.171.10.119.6 }
   extra:
     console_conn_type: dlink
     diag_linkup: true
     console_commands_after_connect:
       - disa clip
   modules:
     parse_interface: \SwitcherCore\Modules\Dlink\ParseInterface
     fdb: \SwitcherCore\Modules\Dlink\Fdb\DefaultParser
     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDgs3420Parser
     interface_counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
     system: \SwitcherCore\Modules\Dlink\System\DefaultParser
     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
     reboot: \SwitcherCore\Modules\Dlink\Reboot
     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts
     ctrl_port_state: \SwitcherCore\Modules\Dlink\StatePortControl
     ctrl_port_speed: \SwitcherCore\Modules\Dlink\SpeedPortControl
     ctrl_port_descr: \SwitcherCore\Modules\Dlink\DescriptionPortControl
     ctrl_vlan_state: \SwitcherCore\Modules\Dlink\VlanStateControl
     ctrl_vlan_port: \SwitcherCore\Modules\Dlink\VlanPortControl
     sys_resources: \SwitcherCore\Modules\Dlink\System\SystemResources
     interface_descriptions: \SwitcherCore\Modules\Dlink\Link\Descriptions
     interfaces_list: \SwitcherCore\Modules\Dlink\InterfacesList
     console_command: \SwitcherCore\Modules\Dlink\RawConsoleCommand
     multi_console_command: \SwitcherCore\Modules\Dlink\MultiRawConsoleCommand
     lldp_info: \SwitcherCore\Modules\Dlink\LldpInfo
     net_settings: \SwitcherCore\Modules\General\NetSettings
     supported_modules: \SwitcherCore\Modules\General\SupportedModules
     sys_temp: \SwitcherCore\Modules\General\SystemTemperatures
     sfp_optical: \SwitcherCore\Modules\Dlink\SfpDiag\SfpOpticalParser
