models:
  - name: Edge-core ECS4120-28F
    key: edgecore_ecs4120_28f
    ports: 26
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ^ECS4120-28F,  objid: .1.3.6.1.4.1.259.10.1.45.103 }
    oids:
      - ./oids/edgecore/ecs4120.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      sfp_media: \SwitcherCore\Modules\Edgecore\SfpMediaInfo
      sfp_optical: \SwitcherCore\Modules\Edgecore\SfpOpticalInfo
      sfp_diag: \SwitcherCore\Modules\Edgecore\SfpDiag

  - name: Edge-core ECS4120-28Fv2
    key: edgecore_ecs4120_28fv2
    ports: 26
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ^ECS4120-28Fv2,  objid: .1.3.6.1.4.1.259.10.1.45.105 }
    oids:
      - ./oids/edgecore/ecs4120.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      sfp_media: \SwitcherCore\Modules\Edgecore\SfpMediaInfo
      sfp_optical: \SwitcherCore\Modules\Edgecore\SfpOpticalInfo
      sfp_diag: \SwitcherCore\Modules\Edgecore\SfpDiag

  - name: Edge-core ECS4510-28F
    key: edgecore_ecs4510_28f
    ports: 26
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ^ECS4510-28F,  objid: .1.3.6.1.4.1.259.10.1.24.103 }
    oids:
      - ./oids/edgecore/ecs4510.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      sfp_media: \SwitcherCore\Modules\Edgecore\SfpMediaInfo
      sfp_optical: \SwitcherCore\Modules\Edgecore\SfpOpticalInfo
      sfp_diag: \SwitcherCore\Modules\Edgecore\SfpDiag

  - name: Edge-core ES4612
    key: edgecore_es4612
    ports: 12
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ^8 SFP ports \+ 4 Gigabit,  objid: .1.3.6.1.4.1.259.6.10.57 }
    oids:
      - ./oids/edgecore/es4612.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      sfp_media: \SwitcherCore\Modules\Edgecore\SfpMediaInfo
      sfp_optical: \SwitcherCore\Modules\Edgecore\SfpOpticalInfo
      sfp_diag: \SwitcherCore\Modules\Edgecore\SfpDiag

  - name: Edge-core ES3552M
    key: edgecore_es3552m
    ports: 52
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: .*ES3552M,  objid: .1.3.6.1.4.1.259.6.10.94 }
    extra:
      diag_linkup: false
      count_pairs: 2
      overwrite_pairs: {ports: [], count_pairs: 4}
    oids:
      - ./oids/edgecore/es3552m.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      cable_diag: \SwitcherCore\Modules\Edgecore\CableDiagOnlyByPort

  - name: Edge-core ECS3510-28T
    key: edgecore_ecs3510_28t
    ports: 28
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ECS3510-28T,  objid: .1.3.6.1.4.1.259.10.1.27.101 }
    extra:
      diag_linkup: false
      count_pairs: 2
      overwrite_pairs: {ports: [25,26,27,28], count_pairs: 4}
    oids:
      - ./oids/edgecore/ecs3510.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      cable_diag: \SwitcherCore\Modules\Edgecore\CableDiagOnlyByPort

  - name: Edge-core ES3528M
    key: edgecore_es3528m
    ports: 52
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: .*ES3528M,  objid: .1.3.6.1.4.1.259.6.10.94 }
    extra:
      diag_linkup: false
      count_pairs: 2
      overwrite_pairs: {ports: [], count_pairs: 4}
    oids:
      - ./oids/edgecore/es3528m.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      cable_diag: \SwitcherCore\Modules\Edgecore\CableDiagOnlyByPort

  - name: Edge-core ES3510MA
    key: edgecore_es3510ma
    ports: 10
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ES3510MA,  objid: .1.3.6.1.4.1.259.8.1.11.101}
    extra:
      diag_linkup: false
      count_pairs: 2
      overwrite_pairs: {ports: [], count_pairs: 4}
    oids:
      - ./oids/edgecore/es3510mav2.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      cable_diag: \SwitcherCore\Modules\Edgecore\CableDiagES3510

  - name: Edge-core ES3510MAv2
    key: edgecore_es3510ma_v2
    ports: 52
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ES3510MAv2,  objid: .1.3.6.1.4.1.259.8.1.11.105 }
    extra:
      diag_linkup: false
      count_pairs: 2
      overwrite_pairs: {ports: [], count_pairs: 4}
    oids:
      - ./oids/edgecore/es3510mav2.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      cable_diag: \SwitcherCore\Modules\Edgecore\CableDiagES3510

  - name: Edge-core ES3510
    key: edgecore_es3510
    ports: 52
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ES3510,  objid: .1.3.6.1.4.1.259.8.1.5 }
    extra:
      diag_linkup: false
      count_pairs: 2
      overwrite_pairs: {ports: [], count_pairs: 4}
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
