models:
  - name: Edgecore ECS4120-28F
    key: edgecore_ecs4120_28f
    ports: 26
    device_type: SWITCH
    inputs:
      - snmp
    detect: {description: ^ECS4120-28F,  objid: .1.3.6.1.4.1.259.10.1.45.103 }
    oids:
      - ./oids/edgecore/ecs4120.yml
    modules:
      system: \SwitcherCore\Modules\Edgecore\System
      parse_interface: \SwitcherCore\Modules\Edgecore\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Edgecore\InterfacesList
      fdb: \SwitcherCore\Modules\Edgecore\Fdb
      link_info: \SwitcherCore\Modules\Edgecore\LinkInfo
      counters: \SwitcherCore\Modules\Edgecore\Counters
      vlans: \SwitcherCore\Modules\Edgecore\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Edgecore\VlanByPorts
      errors: \SwitcherCore\Modules\Edgecore\Errors
      interface_descriptions: \SwitcherCore\Modules\Edgecore\Descriptions
      sys_resources: \SwitcherCore\Modules\Edgecore\SysResources
      rmon: \SwitcherCore\Modules\Edgecore\Rmon
      pvid: \SwitcherCore\Modules\Edgecore\PvidDot1q
      sfp_media: \SwitcherCore\Modules\Edgecore\SfpMediaInfo
      sfp_optical: \SwitcherCore\Modules\Edgecore\SfpOpticalInfo
      sfp_diag: \SwitcherCore\Modules\Edgecore\SfpDiag
