
models:
- name: HP PROCURVE J9079A
  key: hp_procurve_j9079
  device_type: SWITCH
  inputs:
    - snmp
  detect: {description: "PROCURVE J9079A",  objid: ^.1.3.6.1.4.1.11.2.3.7.11 }
  modules:
    parse_interface: \SwitcherCore\Modules\HpSwitch\ParseInterface
    link_info: \SwitcherCore\Modules\HpSwitch\LinkInfo
    interface_counters: \SwitcherCore\Modules\HpSwitch\Counters
    system: \SwitcherCore\Modules\HpSwitch\System
    vlans: \SwitcherCore\Modules\HpSwitch\VlansDot1q
    errors: \SwitcherCore\Modules\HpSwitch\Errors
    rmon: \SwitcherCore\Modules\HpSwitch\Rmon
    pvid: \SwitcherCore\Modules\HpSwitch\PvidDot1q
    vlans_by_port: \SwitcherCore\Modules\HpSwitch\VlanByPorts
    interface_descriptions: \SwitcherCore\Modules\HpSwitch\Descriptions
    interfaces_list: \SwitcherCore\Modules\HpSwitch\InterfacesList
    ctrl_port_descr: \SwitcherCore\Modules\HpSwitch\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\HpSwitch\StatePortControl
    lldp_info: \SwitcherCore\Modules\HpSwitch\LldpInfo
    net_settings: \SwitcherCore\Modules\General\NetSettings
    supported_modules: \SwitcherCore\Modules\General\SupportedModules

- name: HP Switch
  key: hp_general_switch
  device_type: SWITCH
  rewrites:
    oid: .1.3.6.1.2.1.1.1.0
    mapping:
      - value: ^ProCurve J9085A Switch 2610-24
        rewrite:
          key: hp_procurve_j9085a_24
          name: HP ProCurve J9085A Switch 2610-24

      - value: ^ProCurve J9021A Switch 2810-24G
        rewrite:
          key: hp_procurve_j9021a_24
          name: HP ProCurve J9021A Switch 2810-24G

      - value: ^ProCurve j9020a Switch 2510-48
        rewrite:
          key: hp_procurve_j9090a_48
          name: HP ProCurve J9020A Switch 2510-48

      - value: ^HP J9626A 2620-48 Switch
        rewrite:
          key: hp_j9626a_48
          name: HP J9626A 2620-48 Switch
  inputs:
    - snmp
  detect: {description: .*,  objid: ^.1.3.6.1.4.1.11.2.3.7.11 }
  modules:
    parse_interface: \SwitcherCore\Modules\HpSwitch\ParseInterface
    fdb: \SwitcherCore\Modules\HpSwitch\Fdb
    link_info: \SwitcherCore\Modules\HpSwitch\LinkInfo
    interface_counters: \SwitcherCore\Modules\HpSwitch\Counters
    system: \SwitcherCore\Modules\HpSwitch\System
    vlans: \SwitcherCore\Modules\HpSwitch\VlansDot1q
    errors: \SwitcherCore\Modules\HpSwitch\Errors
    rmon: \SwitcherCore\Modules\HpSwitch\Rmon
    pvid: \SwitcherCore\Modules\HpSwitch\PvidDot1q
    vlans_by_port: \SwitcherCore\Modules\HpSwitch\VlanByPorts
    interface_descriptions: \SwitcherCore\Modules\HpSwitch\Descriptions
    interfaces_list: \SwitcherCore\Modules\HpSwitch\InterfacesList
    ctrl_port_descr: \SwitcherCore\Modules\HpSwitch\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\HpSwitch\StatePortControl
    lldp_info: \SwitcherCore\Modules\HpSwitch\LldpInfo
    net_settings: \SwitcherCore\Modules\General\NetSettings
    supported_modules: \SwitcherCore\Modules\General\SupportedModules

- name: HP Switch (ArubaOS)
  key: hp_arubaos_switch
  device_type: SWITCH
  inputs:
    - snmp
  detect: {description: ArubaOS,  objid: ^.1.3.6.1.4.1.14823.1.1 }
  modules:
    parse_interface: \SwitcherCore\Modules\HpArubaOsSwitch\ParseInterface
    fdb: \SwitcherCore\Modules\HpArubaOsSwitch\Fdb
    link_info: \SwitcherCore\Modules\HpArubaOsSwitch\LinkInfo
    interface_counters: \SwitcherCore\Modules\HpArubaOsSwitch\Counters
    system: \SwitcherCore\Modules\HpArubaOsSwitch\System
    vlans: \SwitcherCore\Modules\HpArubaOsSwitch\VlansDot1q
    errors: \SwitcherCore\Modules\HpArubaOsSwitch\Errors
    rmon: \SwitcherCore\Modules\HpArubaOsSwitch\Rmon
    vlans_by_port: \SwitcherCore\Modules\HpArubaOsSwitch\VlanByPorts
    interface_descriptions: \SwitcherCore\Modules\HpArubaOsSwitch\Descriptions
    interfaces_list: \SwitcherCore\Modules\HpArubaOsSwitch\InterfacesList
    ctrl_port_descr: \SwitcherCore\Modules\HpArubaOsSwitch\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\HpArubaOsSwitch\StatePortControl
    lldp_info: \SwitcherCore\Modules\HpSwitch\LldpInfo
    net_settings: \SwitcherCore\Modules\General\NetSettings
    supported_modules: \SwitcherCore\Modules\General\SupportedModules

- name: HPE switch
  key: hpe_switch
  device_type: SWITCH
  inputs:
    - snmp
  detect: {description: ArubaOS,  objid: ^.1.3.6.1.4.1.14823.1.1 }
  modules:
    parse_interface: \SwitcherCore\Modules\HPESwitch\ParseInterface
    fdb: \SwitcherCore\Modules\HPESwitch\Fdb
    link_info: \SwitcherCore\Modules\HPESwitch\LinkInfo
    interface_counters: \SwitcherCore\Modules\HPESwitch\Counters
    system: \SwitcherCore\Modules\HPESwitch\System
    vlans: \SwitcherCore\Modules\HPESwitch\VlansDot1q
    errors: \SwitcherCore\Modules\HPESwitch\Errors
    rmon: \SwitcherCore\Modules\HPESwitch\Rmon
    vlans_by_port: \SwitcherCore\Modules\HPESwitch\VlanByPorts
    interface_descriptions: \SwitcherCore\Modules\HPESwitch\Descriptions
    interfaces_list: \SwitcherCore\Modules\HPESwitch\InterfacesList
    ctrl_port_descr: \SwitcherCore\Modules\HPESwitch\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\HPESwitch\StatePortControl
    lldp_info: \SwitcherCore\Modules\HpSwitch\LldpInfo
    net_settings: \SwitcherCore\Modules\General\NetSettings
    supported_modules: \SwitcherCore\Modules\General\SupportedModules
