models:
  - name: Huawei MA5680T
    key: huawei_ma5680t
    inputs:
      - snmp
      - console
    detect: {description: ^Huawei*,  objid: .1.3.6.1.4.1.2011.2.115 }
    device_type: OLT
    oids:
      - ./oids/huawei/smartax.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiOLT\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\HuaweiOLT\PonPortsList
      parse_interface: \SwitcherCore\Modules\HuaweiOLT\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiOLT\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\HuaweiOLT\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\HuaweiOLT\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\HuaweiOLT\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\HuaweiOLT\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\HuaweiOLT\OntReasons
      pon_onts_down_history: \SwitcherCore\Modules\HuaweiOLT\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\HuaweiOLT\OntVendorInfo
      interface_descriptions: \SwitcherCore\Modules\HuaweiOLT\InterfaceDescriptions
      pon_onts_configuration: \SwitcherCore\Modules\HuaweiOLT\OntConfiguration
#      sys_resources: \SwitcherCore\Modules\HuaweiOLT\SystemResources
      uni_interfaces_status: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesStatus
      interface_counters: \SwitcherCore\Modules\HuaweiOLT\InterfaceCounters
      fdb: \SwitcherCore\Modules\HuaweiOLT\FdbTableConsole
      ctrl_ont_reboot: \SwitcherCore\Modules\HuaweiOLT\OntReboot
      ctrl_ont_delete: \SwitcherCore\Modules\HuaweiOLT\OntDelete
      ctrl_ont_clear_counters: \SwitcherCore\Modules\HuaweiOLT\OntResetCounters
      console_command: \SwitcherCore\Modules\HuaweiOLT\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiOLT\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\HuaweiOLT\GponProfiles
      unregistered_onts: \SwitcherCore\Modules\HuaweiOLT\UnregisteredOnts
      ctrl_ont_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlOntDescription
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlPortDescription
      link_info: \SwitcherCore\Modules\HuaweiOLT\LinkInfo
      card_list: \SwitcherCore\Modules\HuaweiOLT\CardList
      card_status: \SwitcherCore\Modules\HuaweiOLT\CardStatus
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesControlAdminStatus
    extra:
      console_conn_type: huawei_ma
      console_commands_after_connect:
        - enable
        - "scroll \r\n"

  - name: Huawei MA5603T
    key: huawei_ma5603t
    inputs:
      - snmp
      - console
    detect: {description: ^Huawei*,  objid: 1.3.6.1.4.1.2011.2.123 }
    device_type: OLT
    oids:
      - ./oids/huawei/smartax.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiOLT\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\HuaweiOLT\PonPortsList
      parse_interface: \SwitcherCore\Modules\HuaweiOLT\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiOLT\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\HuaweiOLT\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\HuaweiOLT\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\HuaweiOLT\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\HuaweiOLT\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\HuaweiOLT\OntReasons
      pon_onts_down_history: \SwitcherCore\Modules\HuaweiOLT\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\HuaweiOLT\OntVendorInfo
      interface_descriptions: \SwitcherCore\Modules\HuaweiOLT\InterfaceDescriptions
      pon_onts_configuration: \SwitcherCore\Modules\HuaweiOLT\OntConfiguration
      uni_interfaces_status: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesStatus
      interface_counters: \SwitcherCore\Modules\HuaweiOLT\InterfaceCounters
      fdb: \SwitcherCore\Modules\HuaweiOLT\FdbTableConsole
      ctrl_ont_reboot: \SwitcherCore\Modules\HuaweiOLT\OntReboot
      ctrl_ont_clear_counters: \SwitcherCore\Modules\HuaweiOLT\OntResetCounters
      console_command: \SwitcherCore\Modules\HuaweiOLT\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiOLT\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\HuaweiOLT\GponProfiles
      unregistered_onts: \SwitcherCore\Modules\HuaweiOLT\UnregisteredOnts
      ctrl_ont_delete: \SwitcherCore\Modules\HuaweiOLT\OntDelete
      ctrl_ont_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlOntDescription
      link_info: \SwitcherCore\Modules\HuaweiOLT\LinkInfo
      card_list: \SwitcherCore\Modules\HuaweiOLT\CardList
      card_status: \SwitcherCore\Modules\HuaweiOLT\CardStatus
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesControlAdminStatus
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlPortDescription
    extra:
      console_conn_type: huawei_ma
      console_commands_after_connect:
        - enable
        - "scroll \r\n"

  - name: Huawei MA5608T
    key: huawei_ma5608t
    inputs:
      - snmp
      - console
    detect: {description: ^Huawei*,  objid: 1.3.6.1.4.1.2011.2.248 }
    device_type: OLT
    oids:
      - ./oids/huawei/smartax.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiOLT\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\HuaweiOLT\PonPortsList
      parse_interface: \SwitcherCore\Modules\HuaweiOLT\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiOLT\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\HuaweiOLT\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\HuaweiOLT\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\HuaweiOLT\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\HuaweiOLT\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\HuaweiOLT\OntReasons
      pon_onts_down_history: \SwitcherCore\Modules\HuaweiOLT\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\HuaweiOLT\OntVendorInfo
      interface_descriptions: \SwitcherCore\Modules\HuaweiOLT\InterfaceDescriptions
      pon_onts_configuration: \SwitcherCore\Modules\HuaweiOLT\OntConfiguration
      uni_interfaces_status: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesStatus
      interface_counters: \SwitcherCore\Modules\HuaweiOLT\InterfaceCounters
      fdb: \SwitcherCore\Modules\HuaweiOLT\FdbTableConsole
      ctrl_ont_reboot: \SwitcherCore\Modules\HuaweiOLT\OntReboot
      ctrl_ont_clear_counters: \SwitcherCore\Modules\HuaweiOLT\OntResetCounters
      console_command: \SwitcherCore\Modules\HuaweiOLT\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiOLT\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\HuaweiOLT\GponProfiles
      unregistered_onts: \SwitcherCore\Modules\HuaweiOLT\UnregisteredOnts
      ctrl_ont_delete: \SwitcherCore\Modules\HuaweiOLT\OntDelete
      ctrl_ont_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlOntDescription
      link_info: \SwitcherCore\Modules\HuaweiOLT\LinkInfo
      card_list: \SwitcherCore\Modules\HuaweiOLT\CardList
      card_status: \SwitcherCore\Modules\HuaweiOLT\CardStatus
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesControlAdminStatus
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlPortDescription
    extra:
      console_conn_type: huawei_ma
      console_commands_after_connect:
        - enable
        - "scroll \r\n"

  - name: Huawei MA5683T
    key: huawei_ma5683t
    inputs:
      - snmp
      - console
    detect: {description: ^Huawei*,  objid: .1.3.6.1.4.1.2011.2.133 }
    device_type: OLT
    oids:
      - ./oids/huawei/smartax.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiOLT\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\HuaweiOLT\PonPortsList
      parse_interface: \SwitcherCore\Modules\HuaweiOLT\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiOLT\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\HuaweiOLT\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\HuaweiOLT\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\HuaweiOLT\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\HuaweiOLT\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\HuaweiOLT\OntReasons
      pon_onts_down_history: \SwitcherCore\Modules\HuaweiOLT\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\HuaweiOLT\OntVendorInfo
      interface_descriptions: \SwitcherCore\Modules\HuaweiOLT\InterfaceDescriptions
      pon_onts_configuration: \SwitcherCore\Modules\HuaweiOLT\OntConfiguration
#      sys_resources: \SwitcherCore\Modules\HuaweiOLT\SystemResources
      uni_interfaces_status: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesStatus
      interface_counters: \SwitcherCore\Modules\HuaweiOLT\InterfaceCounters
      fdb: \SwitcherCore\Modules\HuaweiOLT\FdbTableConsole
      ctrl_ont_reboot: \SwitcherCore\Modules\HuaweiOLT\OntReboot
      ctrl_ont_clear_counters: \SwitcherCore\Modules\HuaweiOLT\OntResetCounters
      console_command: \SwitcherCore\Modules\HuaweiOLT\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiOLT\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\HuaweiOLT\GponProfiles
      unregistered_onts: \SwitcherCore\Modules\HuaweiOLT\UnregisteredOnts
      ctrl_ont_delete: \SwitcherCore\Modules\HuaweiOLT\OntDelete
      ctrl_ont_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlOntDescription
      link_info: \SwitcherCore\Modules\HuaweiOLT\LinkInfo
      card_list: \SwitcherCore\Modules\HuaweiOLT\CardList
      card_status: \SwitcherCore\Modules\HuaweiOLT\CardStatus
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesControlAdminStatus
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlPortDescription
    extra:
      console_conn_type: huawei_ma
      console_commands_after_connect:
        - enable
        - "scroll \r\n"

  - name: Huawei SmartAX OLT
    key: huawei_smart_ax
    inputs:
      - snmp
      - console
    detect: {description: ^Huawei*,  objid: .1.3.6.1.4.1.2011.2 }
    device_type: OLT
    oids:
      - ./oids/huawei/smartax.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiOLT\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\HuaweiOLT\PonPortsList
      parse_interface: \SwitcherCore\Modules\HuaweiOLT\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiOLT\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\HuaweiOLT\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\HuaweiOLT\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\HuaweiOLT\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\HuaweiOLT\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\HuaweiOLT\OntReasons
      pon_onts_down_history: \SwitcherCore\Modules\HuaweiOLT\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\HuaweiOLT\OntVendorInfo
      interface_descriptions: \SwitcherCore\Modules\HuaweiOLT\InterfaceDescriptions
      pon_onts_configuration: \SwitcherCore\Modules\HuaweiOLT\OntConfiguration
#      sys_resources: \SwitcherCore\Modules\HuaweiOLT\SystemResources
      uni_interfaces_status: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesStatus
      interface_counters: \SwitcherCore\Modules\HuaweiOLT\InterfaceCounters
      fdb: \SwitcherCore\Modules\HuaweiOLT\FdbTableConsole
      ctrl_ont_reboot: \SwitcherCore\Modules\HuaweiOLT\OntReboot
      ctrl_ont_clear_counters: \SwitcherCore\Modules\HuaweiOLT\OntResetCounters
      console_command: \SwitcherCore\Modules\HuaweiOLT\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiOLT\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\HuaweiOLT\GponProfiles
      unregistered_onts: \SwitcherCore\Modules\HuaweiOLT\UnregisteredOnts
      ctrl_ont_delete: \SwitcherCore\Modules\HuaweiOLT\OntDelete
      ctrl_ont_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlOntDescription
      link_info: \SwitcherCore\Modules\HuaweiOLT\LinkInfo
      card_list: \SwitcherCore\Modules\HuaweiOLT\CardList
      card_status: \SwitcherCore\Modules\HuaweiOLT\CardStatus
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesControlAdminStatus
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlPortDescription
    extra:
      console_conn_type: huawei_ma
      console_commands_after_connect:
        - enable
        - "scroll \r\n"

  - name: Huawei MA5801
    key: huawei_ma5801
    inputs:
      - snmp
      - console
    detect: {description: ^Huawei*,  objid: .1.3.6.1.4.1.2011.2.381 }
    device_type: OLT
    oids:
      - ./oids/huawei/smartax.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiOLT\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\HuaweiOLT\PonPortsList
      parse_interface: \SwitcherCore\Modules\HuaweiOLT\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiOLT\InterfacesList
      pon_onts_status: \SwitcherCore\Modules\HuaweiOLT\OntListWithStatuses
      pon_onts_serial: \SwitcherCore\Modules\HuaweiOLT\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\HuaweiOLT\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\HuaweiOLT\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\HuaweiOLT\OntReasons
      pon_onts_down_history: \SwitcherCore\Modules\HuaweiOLT\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\HuaweiOLT\OntVendorInfo
      interface_descriptions: \SwitcherCore\Modules\HuaweiOLT\InterfaceDescriptions
      pon_onts_configuration: \SwitcherCore\Modules\HuaweiOLT\OntConfiguration
      #      sys_resources: \SwitcherCore\Modules\HuaweiOLT\SystemResources
      uni_interfaces_status: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesStatus
      interface_counters: \SwitcherCore\Modules\HuaweiOLT\InterfaceCounters
      fdb: \SwitcherCore\Modules\HuaweiOLT\FdbTableConsole
      ctrl_ont_reboot: \SwitcherCore\Modules\HuaweiOLT\OntReboot
      ctrl_ont_clear_counters: \SwitcherCore\Modules\HuaweiOLT\OntResetCounters
      console_command: \SwitcherCore\Modules\HuaweiOLT\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiOLT\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\HuaweiOLT\GponProfiles
      unregistered_onts: \SwitcherCore\Modules\HuaweiOLT\UnregisteredOnts
      ctrl_ont_delete: \SwitcherCore\Modules\HuaweiOLT\OntDelete
      ctrl_ont_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlOntDescription
      link_info: \SwitcherCore\Modules\HuaweiOLT\LinkInfo
      card_list: \SwitcherCore\Modules\HuaweiOLT\CardList
      card_status: \SwitcherCore\Modules\HuaweiOLT\CardStatus
      ctrl_ont_uni_admin_state: \SwitcherCore\Modules\HuaweiOLT\UniInterfacesControlAdminStatus
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiOLT\CtrlPortDescription
    extra:
      console_conn_type: huawei_ma
      console_commands_after_connect:
        - {command: enable, check_password: true}
        - "scroll \r\n"
