models:
 - name: Huawei S2326TP-EI
   key: huawei_s2326tp_ei
   ports: 26
   device_type: SWITCH
   inputs:
     - snmp
   detect: {description: ^S2326TP-EI.*,  objid: .1.3.6.1.4.1.2011.2.23.92 }
   extra:
     sys_resources_id: 67108873
     sfp_ports:
       - 67240014
       - 67240078
     diag_linkup: false
     only_manual_diag: false
   oids:
     - ./oids/huawei/s2326tp.yml
   modules:
     system: \SwitcherCore\Modules\Huawei\System
     parse_interface: \SwitcherCore\Modules\Huawei\ParseInterface
     interfaces_list: \SwitcherCore\Modules\Huawei\InterfacesList
     fdb: \SwitcherCore\Modules\Huawei\Fdb
     link_info: \SwitcherCore\Modules\Huawei\LinkInfo
     counters: \SwitcherCore\Modules\Huawei\Counters
     vlans: \SwitcherCore\Modules\Huawei\VlansDot1q
     vlans_by_port: \SwitcherCore\Modules\Huawei\VlanByPorts
     errors: \SwitcherCore\Modules\Huawei\Errors
     interface_descriptions: \SwitcherCore\Modules\Huawei\Descriptions
     sys_resources: \SwitcherCore\Modules\Huawei\SysResources
     rmon: \SwitcherCore\Modules\Huawei\Rmon
     pvid: \SwitcherCore\Modules\Huawei\PvidDot1q
     cable_diag: \SwitcherCore\Modules\Huawei\CableDiag
#     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
#     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
#     reboot: \SwitcherCore\Modules\Dlink\Reboot

 - name: Huawei S2320-28TP-EI
   key: huawei_s2320_28tp_ei
   ports: 28
   device_type: SWITCH
   inputs:
     - snmp
   detect: {description: ^S2320-28TP-EI.*,  objid: .1.3.6.1.4.1.2011.2.23.530 }
   extra:
     sys_resources_id: 67108873
     sfp_ports:
       - 67240014
       - 67240078
     diag_linkup: false
     only_manual_diag: true
   oids:
     - ./oids/huawei/s2326tp.yml
   modules:
     system: \SwitcherCore\Modules\Huawei\System
     parse_interface: \SwitcherCore\Modules\Huawei\ParseInterface
     interfaces_list: \SwitcherCore\Modules\Huawei\InterfacesList
     fdb: \SwitcherCore\Modules\Huawei\Fdb
     link_info: \SwitcherCore\Modules\Huawei\LinkInfo
     counters: \SwitcherCore\Modules\Huawei\Counters
     vlans: \SwitcherCore\Modules\Huawei\VlansDot1q
     vlans_by_port: \SwitcherCore\Modules\Huawei\VlanByPorts
     errors: \SwitcherCore\Modules\Huawei\Errors
     interface_descriptions: \SwitcherCore\Modules\Huawei\Descriptions
     sys_resources: \SwitcherCore\Modules\Huawei\SysResources
     rmon: \SwitcherCore\Modules\Huawei\Rmon
     pvid: \SwitcherCore\Modules\Huawei\PvidDot1q
     cable_diag: \SwitcherCore\Modules\Huawei\CableDiag
#     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
#     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
#     reboot: \SwitcherCore\Modules\Dlink\Reboot
