models:
  - name: Huawei general switch
    key: huawei_general_switch
    device_type: SWITCH
    inputs:
      - snmp
      - console
    detect: {description: ^S.*,  objid: .1.3.6.1.4.1.2011.2.23 }
    extra:
      sys_resources_id: 67108873
      sfp_ports:
        - 67240014
        - 67240078
      diag_linkup: false
      only_manual_diag: true
      console_conn_type: huawei
      console_commands_after_connect:
        - screen-length 0 temporary
    rewrites:
      oid: .1.3.6.1.2.1.1.1.0
      mapping:
        - value: ^S2326TP
          rewrite:
            key: huawei_s2326tp_ei
            name: Huawei S2326TP-EI
        - value: ^S2320-28TP
          rewrite:
            key: huawei_s2320_28tp_ei
            name: Huawei S2320-28TP-EI
        - value: ^S2350-28TP-EI-AC
          rewrite:
            key: huawei_s2350_28tp
            name: Huawei S2350-28TP-EI-AC
    oids:
      - ./oids/huawei/s2326tp.yml
    modules:
      system: \SwitcherCore\Modules\Huawei\System
      parse_interface: \SwitcherCore\Modules\Huawei\ParseInterface
      interfaces_list: \SwitcherCore\Modules\Huawei\InterfacesList
      fdb: \SwitcherCore\Modules\Huawei\Fdb
      link_info: \SwitcherCore\Modules\Huawei\LinkInfo
      interface_counters: \SwitcherCore\Modules\Huawei\Counters
      vlans: \SwitcherCore\Modules\Huawei\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\Huawei\VlanByPorts
      errors: \SwitcherCore\Modules\Huawei\Errors
      interface_descriptions: \SwitcherCore\Modules\Huawei\Descriptions
      sys_resources: \SwitcherCore\Modules\Huawei\SysResources
      rmon: \SwitcherCore\Modules\Huawei\Rmon
      pvid: \SwitcherCore\Modules\Huawei\PvidDot1q
      cable_diag: \SwitcherCore\Modules\Huawei\CableDiag
      ctrl_port_descr: \SwitcherCore\Modules\Huawei\SetPortDescription
      ctrl_port_state: \SwitcherCore\Modules\Huawei\StatePortControl
      clear_counters: \SwitcherCore\Modules\Huawei\ClearCounters
      reboot: \SwitcherCore\Modules\Huawei\Reboot
      console_command: \SwitcherCore\Modules\Huawei\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\Huawei\MultiRawConsoleCommand

  - name: Huawei Quidway S9300 series
    key: huawei_quidway_S9300_series
    device_type: SWITCH
    inputs:
      - snmp
      - console
    detect: {description: ^Quidway S93.*,  objid: .1.3.6.1.4.1.2011.2 }
    extra:
      console_conn_type: huawei
      console_commands_after_connect:
        - screen-length 0 temporary
    oids:
      - ./oids/huawei/s2326tp.yml
    modules:
      system: \SwitcherCore\Modules\HuaweiQuidwayS93\System
      parse_interface: \SwitcherCore\Modules\HuaweiQuidwayS93\ParseInterface
      interfaces_list: \SwitcherCore\Modules\HuaweiQuidwayS93\InterfacesList
      fdb: \SwitcherCore\Modules\HuaweiQuidwayS93\Fdb
      link_info: \SwitcherCore\Modules\HuaweiQuidwayS93\LinkInfo
      interface_counters: \SwitcherCore\Modules\HuaweiQuidwayS93\Counters
      vlans: \SwitcherCore\Modules\HuaweiQuidwayS93\VlansDot1q
      vlans_by_port: \SwitcherCore\Modules\HuaweiQuidwayS93\VlanByPorts
      errors: \SwitcherCore\Modules\HuaweiQuidwayS93\Errors
      interface_descriptions: \SwitcherCore\Modules\HuaweiQuidwayS93\Descriptions
      pvid: \SwitcherCore\Modules\HuaweiQuidwayS93\PvidDot1q
      ctrl_port_descr: \SwitcherCore\Modules\HuaweiQuidwayS93\SetPortDescription
      ctrl_port_state: \SwitcherCore\Modules\HuaweiQuidwayS93\StatePortControl
      console_command: \SwitcherCore\Modules\HuaweiQuidwayS93\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\HuaweiQuidwayS93\MultiRawConsoleCommand