models:
 - name: Huawei S2326TP-EI
   key: huawei_s2326tp_ei
   ports: 26
   device_type: SWITCH
   inputs:
     - snmp
     - console
   detect: {description: ^S2326TP-EI.*,  objid: .1.3.6.1.4.1.2011.2.23.92 }
   extra:
     console_conn_type: huawei
   oids:
     - ./oids/huawei/s2326tp.yml
   modules:
     system: \SwitcherCore\Modules\Huawei\System
     parse_interface: \SwitcherCore\Modules\Huawei\ParseInterface
     fdb: \SwitcherCore\Modules\Huawei\Fdb
#     link_info: \SwitcherCore\Modules\Dlink\Link\DlinkDgs3420Parser
#     counters: \SwitcherCore\Modules\Dlink\Counters\DefaultParser
#     vlans: \SwitcherCore\Modules\Dlink\Vlan\DlinkVlanParser
#     cable_diag: \SwitcherCore\Modules\Dlink\CableDiag\DlinkParser
#     errors: \SwitcherCore\Modules\Dlink\Errors\DefaultParser
#     rmon: \SwitcherCore\Modules\Dlink\Rmon\DefaultParser
#     pvid: \SwitcherCore\Modules\Dlink\Vlan\PvidParser
#     clear_counters: \SwitcherCore\Modules\Dlink\ClearCounters
#     save_config: \SwitcherCore\Modules\Dlink\SaveConfig
#     reboot: \SwitcherCore\Modules\Dlink\Reboot
#     vlans_by_port: \SwitcherCore\Modules\Dlink\Vlan\VlanByPorts