
models:
- name: Juniper QFX5100 series
  key: juniper_qfx51xx_series
  device_type: SWITCH
  inputs:
    - snmp
    - console
  detect: {description: Juniper.*qfx51,  objid: ^.1.3.6.1.4.1.2636.1.1.1.4.82 }
  oids:
    - ./oids/juniper.yml
  extra:
    console_conn_type: junos
    console_commands_after_connect:
      - set cli screen-length 0
  modules:
    parse_interface: \SwitcherCore\Modules\Juniper\ParseInterface
    link_info: \SwitcherCore\Modules\Juniper\LinkInfo
    interface_counters: \SwitcherCore\Modules\Juniper\Counters
    system: \SwitcherCore\Modules\Juniper\System
    vlans: \SwitcherCore\Modules\Juniper\VlanList
    errors: \SwitcherCore\Modules\Juniper\Errors
    rmon: \SwitcherCore\Modules\Juniper\Rmon
    pvid: \SwitcherCore\Modules\Juniper\PvidDot1q
    interface_descriptions: \SwitcherCore\Modules\Juniper\Descriptions
    interfaces_list: \SwitcherCore\Modules\Juniper\InterfacesList
    ctrl_port_descr: \SwitcherCore\Modules\Juniper\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\Juniper\StatePortControl
    console_command: \SwitcherCore\Modules\Juniper\RawConsoleCommand
    multi_console_command: \SwitcherCore\Modules\Juniper\MultiRawConsoleCommand
    lldp_info: \SwitcherCore\Modules\Juniper\LldpInfo
    net_settings: \SwitcherCore\Modules\General\NetSettings
    arps: \SwitcherCore\Modules\Juniper\ArpInfo
    bgp_info: \SwitcherCore\Modules\Juniper\BgpInfo
    bgp_peers: \SwitcherCore\Modules\Juniper\BgpPeers
    direct_routes: \SwitcherCore\Modules\Juniper\DirectRoutes
    supported_modules: \SwitcherCore\Modules\General\SupportedModules
    sfp_media: \SwitcherCore\Modules\Juniper\SfpMediaInfo
    sfp_optical: \SwitcherCore\Modules\Juniper\SfpOpticalInfo
    sfp_diag: \SwitcherCore\Modules\General\SfpDiag
    sys_temp: \SwitcherCore\Modules\General\SystemTemperatures
    fdb: \SwitcherCore\Modules\Juniper\Fdb

- name: Juniper JNP204 series
  key: juniper_jnp204_series
  device_type: ROUTER
  oids:
    - ./oids/juniper.yml
  inputs:
    - snmp
    - console
  detect: {description: .*,  objid: ^.1.3.6.1.4.1.2636.1.1.1.2.144 }
  extra:
    console_conn_type: junos
    console_commands_after_connect:
      - set cli screen-length 0
  modules:
    parse_interface: \SwitcherCore\Modules\Juniper\ParseInterface
    link_info: \SwitcherCore\Modules\Juniper\LinkInfo
    interface_counters: \SwitcherCore\Modules\Juniper\Counters
    system: \SwitcherCore\Modules\Juniper\System
    vlans: \SwitcherCore\Modules\Juniper\VlanList
    errors: \SwitcherCore\Modules\Juniper\Errors
    rmon: \SwitcherCore\Modules\Juniper\Rmon
    pvid: \SwitcherCore\Modules\Juniper\PvidDot1q
    interface_descriptions: \SwitcherCore\Modules\Juniper\Descriptions
    interfaces_list: \SwitcherCore\Modules\Juniper\InterfacesList
    ctrl_port_descr: \SwitcherCore\Modules\Juniper\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\Juniper\StatePortControl
    console_command: \SwitcherCore\Modules\Juniper\RawConsoleCommand
    multi_console_command: \SwitcherCore\Modules\Juniper\MultiRawConsoleCommand
    lldp_info: \SwitcherCore\Modules\Juniper\LldpInfo
    arps: \SwitcherCore\Modules\Juniper\ArpInfo
    bgp_info: \SwitcherCore\Modules\Juniper\BgpInfo
    bgp_peers: \SwitcherCore\Modules\Juniper\BgpPeers
    direct_routes: \SwitcherCore\Modules\Juniper\DirectRoutes
    supported_modules: \SwitcherCore\Modules\General\SupportedModules
    sfp_media: \SwitcherCore\Modules\Juniper\SfpMediaInfo
    sfp_optical: \SwitcherCore\Modules\Juniper\SfpOpticalInfo
    sfp_diag: \SwitcherCore\Modules\General\SfpDiag
    sys_temp: \SwitcherCore\Modules\General\SystemTemperatures
    fdb: \SwitcherCore\Modules\Juniper\Fdb




