
models:
- name: UBNT EdgeSwitch
  key: ubnt_edge_switch
  device_type: SWITCH
  inputs:
    - snmp
  detect: {description: EdgeSwitch,  objid: ^.1.3.6.1.4.1.4413 }
  modules:
    parse_interface: \SwitcherCore\Modules\UbntSwitch\ParseInterface
    fdb: \SwitcherCore\Modules\UbntSwitch\Fdb
    link_info: \SwitcherCore\Modules\UbntSwitch\LinkInfo
    interface_counters: \SwitcherCore\Modules\UbntSwitch\Counters
    system: \SwitcherCore\Modules\UbntSwitch\System
    errors: \SwitcherCore\Modules\UbntSwitch\Errors
    rmon: \SwitcherCore\Modules\UbntSwitch\Rmon
    interface_descriptions: \SwitcherCore\Modules\UbntSwitch\Descriptions
    interfaces_list: \SwitcherCore\Modules\UbntSwitch\InterfacesList
    vlans: \SwitcherCore\Modules\UbntSwitch\VlansDot1q
    vlans_by_port: \SwitcherCore\Modules\UbntSwitch\VlanByPorts
    ctrl_port_descr: \SwitcherCore\Modules\UbntSwitch\SetPortDescription
    ctrl_port_state: \SwitcherCore\Modules\UbntSwitch\StatePortControl
    lldp_info: \SwitcherCore\Modules\UbntSwitch\LldpInfo
    net_settings: \SwitcherCore\Modules\General\NetSettings
    supported_modules: \SwitcherCore\Modules\General\SupportedModules

