models:
  - name: V-Solution OLT V1600 series
    key: v_solution_v1600d
    inputs:
      - snmp
      - console
    detect:
      description: ^V1600
      objid: .1.3.6.1.4.1.37950.1.1.5.10.14.1
    rewrites:
      oid: .1.3.6.1.4.1.37950.1.1.5.10.14.1.0
      mapping:
        - value: V1600D8
          rewrite:
            key: v_solution_v1600d8
            name: V-Solution V1600D8
        - value: V1600D16
          rewrite:
            key: v_solution_v1600d16
            name: V-Solution V1600D16
    device_type: OLT
    oids:
      - ./oids/vsolution/v1600d.yml
    modules:
      system: \SwitcherCore\Modules\VsolOlts\SystemInformation
      pon_ports_list: \SwitcherCore\Modules\VsolOlts\PonPortsList
      pon_count_registered_onts: \SwitcherCore\Modules\VsolOlts\PortCountRegisteredOnts
      pon_onts_status: \SwitcherCore\Modules\VsolOlts\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\VsolOlts\OntMacAddress
      pon_onts_optical: \SwitcherCore\Modules\VsolOlts\OntOpticalInfo
      pon_ports_optical: \SwitcherCore\Modules\VsolOlts\PonPortsOptical
      pon_onts_reasons: \SwitcherCore\Modules\VsolOlts\OntReasons
      pon_onts_vendor: \SwitcherCore\Modules\VsolOlts\OntVendorInfo
      fdb: \SwitcherCore\Modules\VsolOlts\FdbTableConsole
      save_config: \SwitcherCore\Modules\VsolOlts\OltSaveSettings
      pon_ont_reboot: \SwitcherCore\Modules\VsolOlts\OntReboot
      pon_ont_reset: \SwitcherCore\Modules\VsolOlts\OntReset
      pon_ont_delete: \SwitcherCore\Modules\VsolOlts\OntDelete
      parse_interface: \SwitcherCore\Modules\VsolOlts\ParseInterface
      sys_resources: \SwitcherCore\Modules\VsolOlts\SystemResources
      interface_counters: \SwitcherCore\Modules\VsolOlts\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\VsolOlts\InterfacesList
      interface_descriptions: \SwitcherCore\Modules\VsolOlts\InterfaceDescriptions
      uni_interfaces_status: \SwitcherCore\Modules\VsolOlts\UniInterfacesStatus
      uni_interfaces_vlans: \SwitcherCore\Modules\VsolOlts\UniInterfacesVlans
    extra:
      console_conn_type: vsolution
      console_commands_after_connect:
        - terminal length 0
