models:
  - name: ZTE C320
    key: zte_c320
    device_type: OLT
    detect: {description: ZTE,  objid: .*\.1001\.320\.2\.1$ }
    oids:
      - ./oids/zte/ZTE-C300_fw2.1.yml
    inputs:
      - snmp
      - console
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatusesV2
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfoV1
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE C300
    key: zte_c300
    device_type: OLT
    detect: {description: C300,  objid: 1082.1001.300.2.1$ }
    oids:
      - ./oids/zte/ZTE-C300_fw2.1.yml
    inputs:
      - snmp
      - console
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatusesV2
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfoV1
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE C320 (FW 1.2)
    key: zte_c320_fw_1_2
    device_type: OLT
    detect: {description: ZTE,  objid: .*\.320.1.2$ }
    oids:
      - ./oids/zte/ZTE-C300_fw1.2.yml
    inputs:
      - snmp
      - console
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatusesV2
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfoV1
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE C300 (FW 1.2)
    key: zte_c300_fw_1_2
    device_type: OLT
    detect: {description: ZTE,  objid: .*\.1015.300.3.1$ }
    oids:
      - ./oids/zte/ZTE-C300_fw1.2.yml
    inputs:
      - snmp
      - console
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatusesV2
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfoV1
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0
