models:
  - name: ZTE ZXPON C220
    key: zte_c220
    ports: 0
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C300.yml
    inputs:
      - snmp
      - console
    detect: {description: C220.*,  objid: .3902.1015.3.1.220.1.2$ }
    modules:
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      onu_reboot: \SwitcherCore\Modules\ZTE\Old\C300Series\RebootOnu
      zte_onu_info: \SwitcherCore\Modules\ZTE\Old\C200Series\OntInfo
      zte_onu_ether_iface_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuEtherPortInfo
      fdb: \SwitcherCore\Modules\ZTE\Old\C200Series\Fdb
      zte_onu_signal_strength: \SwitcherCore\Modules\ZTE\Old\C200Series\OnuSignalStrengthInfo
      zte_onu_state_by_interface: \SwitcherCore\Modules\ZTE\Old\C200Series\OntStateInfo
      zte_onu_dereg: \SwitcherCore\Modules\ZTE\Old\C300Series\DeregOnt
      unregistered_onts: \SwitcherCore\Modules\ZTE\Old\C300Series\UnregisteredOntList
      zte_gpon_onu_profile_list: \SwitcherCore\Modules\ZTE\Old\C300Series\GponOntProfileList
      zte_onu_interface_console: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInterfaceConfCommand
      zte_onu_registration_gpon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationGPON
      zte_onu_registration_epon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationEPON
      save_config: \SwitcherCore\Modules\ZTE\Old\C300Series\SaveConfig
      zte_card_list: \SwitcherCore\Modules\ZTE\Old\C300Series\CardList
      interfaces_list: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesList
      interfaces_status: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesStatus
      zte_interface_running_config: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceRunningConfig
      zte_fully_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuFullyInfo
      zte_pon_power_attenuation: \SwitcherCore\Modules\ZTE\Old\C300Series\PonPowerAttenuation
      console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\MultiRawConsoleCommand
      zte_interface_parser: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceParser
      interface_descriptions: \SwitcherCore\Modules\ZTE\Old\C200Series\InterfaceDescriptions
    extra:
      console_conn_type: zte_—Å220
      port_offset: 0
      card_types:
        - {name: EPFCB, interface_type: epon, count_ports: 4}

  - name: ZTE ZXPON C300
    key: zte_c300
    ports: 0
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C300.yml
    inputs:
      - snmp
      - console
    detect: {description: C300.*,  objid: 3902.1082.1001.300.2.1 }
    modules:
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      onu_reboot: \SwitcherCore\Modules\ZTE\Old\C300Series\RebootOnu
      zte_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInfo
      zte_onu_ether_iface_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuEtherPortInfo
      fdb: \SwitcherCore\Modules\ZTE\Old\C300Series\Fdb
      zte_onu_signal_strength: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuSignalStrengthInfo
      zte_onu_state_by_interface: \SwitcherCore\Modules\ZTE\Old\C300Series\OntStateInfo
      zte_onu_dereg: \SwitcherCore\Modules\ZTE\Old\C300Series\DeregOnt
      unregistered_onts: \SwitcherCore\Modules\ZTE\Old\C300Series\UnregisteredOntList
      zte_gpon_onu_profile_list: \SwitcherCore\Modules\ZTE\Old\C300Series\GponOntProfileList
      zte_onu_interface_console: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInterfaceConfCommand
      zte_onu_registration_gpon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationGPON
      zte_onu_registration_epon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationEPON
      save_config: \SwitcherCore\Modules\ZTE\Old\C300Series\SaveConfig
      zte_card_list: \SwitcherCore\Modules\ZTE\Old\C300Series\CardList
      interfaces_list: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesList
      interfaces_status: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesStatus
      zte_interface_running_config: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceRunningConfig
      zte_fully_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuFullyInfo
      zte_pon_power_attenuation: \SwitcherCore\Modules\ZTE\Old\C300Series\PonPowerAttenuation
      console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\MultiRawConsoleCommand
      zte_interface_parser: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceParser
      interface_descriptions: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceDescriptions
    extra:
      console_conn_type: zte
      port_offset: 0
      card_types:
        - {name: ETGOD, interface_type: epon, count_ports: 8}
        - {name: GTGOG, interface_type: gpon, count_ports: 8}
        - {name: GTGOE, interface_type: gpon, count_ports: 8}
        - {name: GTGHG, interface_type: gpon, count_ports: 16}
        - {name: GTGH, interface_type: gpon, count_ports: 16}
        - {name: GTGHK, interface_type: gpon, count_ports: 16}
        - {name: GFBH, interface_type: gpon, count_ports: 16}
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE ZXPON C320
    key: zte_c320
    ports: 0
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C300.yml
    inputs:
      - snmp
      - console
    detect: {description: C320.*,  objid: .3902.1082.1001.320.2.1$ }
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfo
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList

      zte_onu_info: \SwitcherCore\Modules\ZTE\C300Series\OntInfo
      zte_onu_ether_iface_info: \SwitcherCore\Modules\ZTE\C300Series\OnuEtherPortInfo
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      zte_onu_signal_strength: \SwitcherCore\Modules\ZTE\C300Series\OnuSignalStrengthInfo
      zte_onu_state_by_interface: \SwitcherCore\Modules\ZTE\C300Series\OntStateInfo
      zte_onu_dereg: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      zte_gpon_onu_profile_list: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      zte_onu_interface_console: \SwitcherCore\Modules\ZTE\C300Series\OntInterfaceConfCommand
      zte_onu_registration_gpon: \SwitcherCore\Modules\ZTE\C300Series\OntRegistrationGPON
      zte_onu_registration_epon: \SwitcherCore\Modules\ZTE\C300Series\OntRegistrationEPON
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\InterfacesStatus
      zte_interface_running_config: \SwitcherCore\Modules\ZTE\C300Series\InterfaceRunningConfig
      zte_fully_onu_info: \SwitcherCore\Modules\ZTE\C300Series\OnuFullyInfo
      zte_pon_power_attenuation: \SwitcherCore\Modules\ZTE\C300Series\PonPowerAttenuation
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      onu_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE ZXPON C320
    key: zte_c320_fw_1_2
    ports: 0
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C300.yml
    inputs:
      - snmp
      - console
    detect: {description: .*C320.*,  objid: .1.3.6.1.4.1.3902.1015.320.1.2 }
    modules:
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      onu_reboot: \SwitcherCore\Modules\ZTE\Old\C300Series\RebootOnu
      zte_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInfo
      zte_onu_ether_iface_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuEtherPortInfo
      fdb: \SwitcherCore\Modules\ZTE\Old\C300Series\Fdb
      zte_onu_signal_strength: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuSignalStrengthInfoFW12
      zte_onu_state_by_interface: \SwitcherCore\Modules\ZTE\Old\C300Series\OntStateInfoFW12
      zte_onu_dereg: \SwitcherCore\Modules\ZTE\Old\C300Series\DeregOnt
      unregistered_onts: \SwitcherCore\Modules\ZTE\Old\C300Series\UnregisteredOntList
      zte_gpon_onu_profile_list: \SwitcherCore\Modules\ZTE\Old\C300Series\GponOntProfileList
      zte_onu_interface_console: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInterfaceConfCommand
      zte_onu_registration_gpon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationGPON
      zte_onu_registration_epon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationEPON
      save_config: \SwitcherCore\Modules\ZTE\Old\C300Series\SaveConfig
      zte_card_list: \SwitcherCore\Modules\ZTE\Old\C300Series\CardList
      interfaces_list: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesList
      interfaces_status: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesStatus
      zte_interface_running_config: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceRunningConfig
      zte_fully_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuFullyInfo
      zte_pon_power_attenuation: \SwitcherCore\Modules\ZTE\Old\C300Series\PonPowerAttenuation
      console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\MultiRawConsoleCommand
      zte_interface_parser: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceParser
      interface_descriptions: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceDescriptions
    extra:
      console_conn_type: zte
      port_offset: 1
      card_types:
        - {name: ETGOD, interface_type: epon, count_ports: 8}
        - {name: GTGOG, interface_type: gpon, count_ports: 8}
        - {name: GTGOE, interface_type: gpon, count_ports: 8}
        - {name: GTGHG, interface_type: gpon, count_ports: 16}
        - {name: GTGH, interface_type: gpon, count_ports: 16}
        - {name: GTGHK, interface_type: gpon, count_ports: 16}
        - {name: GFBH, interface_type: gpon, count_ports: 16}
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE ZXPON C300
    key: zte_c300_fw_1_2
    ports: 0
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C300.yml
    inputs:
      - snmp
      - console
    detect: {description: .*C300.*,  objid:  .1.3.6.1.4.1.3902.1015.300.3.1 }
    modules:
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      onu_reboot: \SwitcherCore\Modules\ZTE\Old\C300Series\RebootOnu
      zte_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInfoC300Fw12
      zte_onu_ether_iface_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuEtherPortInfo
      fdb: \SwitcherCore\Modules\ZTE\Old\C300Series\Fdb
      zte_onu_signal_strength: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuSignalStrengthInfoFW12
      zte_onu_state_by_interface: \SwitcherCore\Modules\ZTE\Old\C300Series\OntStateInfoFW12
      zte_onu_dereg: \SwitcherCore\Modules\ZTE\Old\C300Series\DeregOnt
      unregistered_onts: \SwitcherCore\Modules\ZTE\Old\C300Series\UnregisteredOntList
      zte_gpon_onu_profile_list: \SwitcherCore\Modules\ZTE\Old\C300Series\GponOntProfileList
      zte_onu_interface_console: \SwitcherCore\Modules\ZTE\Old\C300Series\OntInterfaceConfCommand
      zte_onu_registration_gpon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationGPON
      zte_onu_registration_epon: \SwitcherCore\Modules\ZTE\Old\C300Series\OntRegistrationEPON
      save_config: \SwitcherCore\Modules\ZTE\Old\C300Series\SaveConfig
      zte_card_list: \SwitcherCore\Modules\ZTE\Old\C300Series\CardList
      interfaces_list: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesList
      interfaces_status: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfacesStatus
      zte_interface_running_config: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceRunningConfig
      zte_fully_onu_info: \SwitcherCore\Modules\ZTE\Old\C300Series\OnuFullyInfo
      zte_pon_power_attenuation: \SwitcherCore\Modules\ZTE\Old\C300Series\PonPowerAttenuation
      console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\Old\C300Series\MultiRawConsoleCommand
      zte_interface_parser: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceParser
      interface_descriptions: \SwitcherCore\Modules\ZTE\Old\C300Series\InterfaceDescriptions
    extra:
      console_conn_type: zte
      port_offset: 1
      card_types:
        - {name: ETGOD, interface_type: epon, count_ports: 8}
        - {name: GTGOG, interface_type: gpon, count_ports: 8}
        - {name: GTGOE, interface_type: gpon, count_ports: 8}
        - {name: GTGHG, interface_type: gpon, count_ports: 16}
        - {name: GTGH, interface_type: gpon, count_ports: 16}
        - {name: GTGHK, interface_type: gpon, count_ports: 16}
        - {name: GFBH, interface_type: gpon, count_ports: 16}
      console_commands_after_connect:
        - terminal length 0
