models:
  - name: ZTE C320
    key: zte_c320
    device_type: OLT
    detect: {description: ZTE,  objid: .*\.1001\.320\.2\.1$ }
    oids:
      - ./oids/zte/ZTE-C300_fw2.1.yml
    inputs:
      - snmp
      - console
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatusesV1
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfo
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE C320 (FW 1.2)
    key: zte_c320_fw_1_2
    device_type: OLT
    detect: {description: ZTE,  objid: .*\.320.1.2$ }
    oids:
      - ./oids/zte/ZTE-C300_fw1.2.yml
    inputs:
      - snmp
      - console
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatusesV1
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfoV1
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0

  - name: ZTE ZXPON OLT
    key: zte_zxpon_olt_series
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C600.yml
    detect: {description: ZTE.*,  objid: .3902.1082.1001.610 }
    inputs:
      - snmp
      - console
    rewrites:
      oid: .1.3.6.1.2.1.1.2.0
      mapping:
        - value: .1001.610.1.1$
          rewrite:
            key: zte_c610_121
            name: ZTE 610 (FW 1.2.1)
            extra:
              console_conn_type: zte
              port_offset: 0
              console_commands_after_connect:
                - terminal length 0
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C600Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C600Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C600Series\PonPortsList
      interfaces_list: \SwitcherCore\Modules\ZTE\C600Series\InterfacesList
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C600Series\OntSerial
      interface_descriptions: \SwitcherCore\Modules\ZTE\C600Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C600Series\InterfaceCounters
      parse_interface: \SwitcherCore\Modules\ZTE\C600Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C600Series\OntListWithStatuses
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C600Series\OntOpticalInfo
      unregistered_onts: \SwitcherCore\Modules\ZTE\C600Series\UnregisteredOntList
      ctrl_ont_delete: \SwitcherCore\Modules\ZTE\C600Series\DeregOnt
      ctrl_ont_reboot: \SwitcherCore\Modules\ZTE\C600Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C600Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C600Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C600Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C600Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C600Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C600Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C600Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C600Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C600Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C600Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C600Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0