models:
  - name: ZTE ZXPON OLT C300 series
    key: zte_olt_c300_series
    device_type: OLT
    oids:
      - ./oids/zte/ZTE-C300.yml
    detect: {description: ZTE.*,  objid: .3902.1082.1001 }
    inputs:
      - snmp
      - console
    rewrites:
      oid:  .1.3.6.1.2.1.1.2
      mapping:
        # FW 1.2
        - value: .*\1001\.220\.1\.2$
          rewrite:
            key: zte_c220_fw_1_2
            name: ZTE C220 (FW 1.2)
            extra:
              console_conn_type: zte_—Å220
              port_offset: 0
              console_commands_after_connect:
                - terminal length 0
        - value: .*\.1001\.300\.1\.2$
          rewrite:
            key: zte_c300_fw_1_2
            name: ZTE C300 (FW 1.2)
        - value: .*\.320.1.2$
          rewrite:
            key: zte_c320_fw_1_2
            name: ZTE C320 (FW 1.2)

        # FW 2.1
        - value: .*\.1001\.220\.2\.1$
          rewrite:
            key: zte_c220
            name: ZTE C220
            extra:
              console_conn_type: zte
              port_offset: 0
              console_commands_after_connect:
                - terminal length 0
        - value: .*\.1001\.300\.2\.1$
          rewrite:
            key: zte_c300
            name: ZTE C300
            extra:
              console_conn_type: zte
              port_offset: 0
              console_commands_after_connect:
                - terminal length 0
        - value: .*\.1001\.320\.2\.1$
          rewrite:
            key: zte_c320
            name: ZTE C320
    modules:
      card_list: \SwitcherCore\Modules\ZTE\C300Series\CardList
      card_status: \SwitcherCore\Modules\ZTE\C300Series\CardStatus
      system: \SwitcherCore\Modules\Dlink\System\DefaultParser
      pon_ports_list: \SwitcherCore\Modules\ZTE\C300Series\PonPortsList
      interface_descriptions: \SwitcherCore\Modules\ZTE\C300Series\InterfaceDescriptions
      interface_counters: \SwitcherCore\Modules\ZTE\C300Series\InterfaceCounters
      interfaces_list: \SwitcherCore\Modules\ZTE\C300Series\InterfacesList
      parse_interface: \SwitcherCore\Modules\ZTE\C300Series\InterfaceParser
      pon_onts_status: \SwitcherCore\Modules\ZTE\C300Series\OntListWithStatuses
      pon_onts_mac_addr: \SwitcherCore\Modules\ZTE\C300Series\OntMacAddress
      pon_onts_serial: \SwitcherCore\Modules\ZTE\C300Series\OntSerial
      pon_onts_optical: \SwitcherCore\Modules\ZTE\C300Series\OntOpticalInfo
      unregistered_onts: \SwitcherCore\Modules\ZTE\C300Series\UnregisteredOntList
      pon_ont_delete: \SwitcherCore\Modules\ZTE\C300Series\DeregOnt
      pon_ont_reboot: \SwitcherCore\Modules\ZTE\C300Series\RebootOnu
      save_config: \SwitcherCore\Modules\ZTE\C300Series\SaveConfig
      console_command: \SwitcherCore\Modules\ZTE\C300Series\RawConsoleCommand
      multi_console_command: \SwitcherCore\Modules\ZTE\C300Series\MultiRawConsoleCommand
      gpon_profiles: \SwitcherCore\Modules\ZTE\C300Series\GponOntProfileList
      fdb: \SwitcherCore\Modules\ZTE\C300Series\Fdb
      pon_onts_reasons: \SwitcherCore\Modules\ZTE\C300Series\OntReasons
      pon_onts_configuration: \SwitcherCore\Modules\ZTE\C300Series\OntConfiguration
      pon_onts_down_history: \SwitcherCore\Modules\ZTE\C300Series\OntDownHistory
      pon_onts_vendor: \SwitcherCore\Modules\ZTE\C300Series\OntVendorInfo
      uni_interfaces_status: \SwitcherCore\Modules\ZTE\C300Series\UniInterfacesStatus
      zte_ont_info: \SwitcherCore\Modules\ZTE\C300Series\ZteConsoleOntInfo
    extra:
      console_conn_type: zte
      port_offset: 1
      console_commands_after_connect:
        - terminal length 0