
- {name: agent.CpuUtilization5sec, oid: .1.3.6.1.4.1.171.12.1.1.6.1 }
- {name: agent.CpuUtilization1min, oid: .1.3.6.1.4.1.171.12.1.1.6.2 }
- {name: agent.CpuUtilization5min, oid: .1.3.6.1.4.1.171.12.1.1.6.3 }

- {name: agent.DramUtilizationTotalDRAM, oid: .1.3.6.1.4.1.171.12.1.1.9.1.2 }
- {name: agent.DramUtilizationUsedDRAM, oid: .1.3.6.1.4.1.171.12.1.1.9.1.3 }
- {name: agent.DramUtilization, oid: .1.3.6.1.4.1.171.12.1.1.9.1.4 }

- {name: agent.PortUtilizationTx, oid: .1.3.6.1.4.1.171.12.1.1.8.1.2 }
- {name: agent.PortUtilizationRx, oid: .1.3.6.1.4.1.171.12.1.1.8.1.3 }
- {name: agent.PortUtilizationUtil, oid: .1.3.6.1.4.1.171.12.1.1.8.1.4 }

- {name: sys.serialNum, oid: .1.3.6.1.4.1.171.12.1.1.12}

- {name: sensors.temperature.cpu, oid: .1.3.6.1.4.1.171.12.11.1.8.1.2.1}

- { name: sfp.ddm.rxPower, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.6}
- { name: sfp.ddm.txPower, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.5}
- { name: sfp.ddm.temp, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.2}
- { name: sfp.ddm.voltage, oid: .1.3.6.1.4.1.171.12.72.2.1.1.1.3}