- {name: sys.macAddr, oid: .1.3.6.1.4.1.171.10.94.89.89.2.12}

- {name: dlink.if.duplexAdminMode, oid: .1.3.6.1.4.1.171.10.94.89.89.43.1.1.3, values: {1: Auto, 2: Half, 3: Full}}
- {name: dlink.if.duplexOperMode, oid: .1.3.6.1.4.1.171.10.94.89.89.43.1.1.4, values: {1: Half, 2: Full, 3: Hybrid, 4: Unknown}}
- {name: dlink.if.duplexOperMode, oid: .1.3.6.1.4.1.171.10.94.89.89.43.1.1.4, values: {1: Half, 2: Full, 3: Hybrid, 4: Unknown}}


- {name: agent.CpuUtilization5sec, oid: .1.3.6.1.4.1.171.10.94.89.89.1.7.0 }
- {name: agent.CpuUtilization1min, oid: .1.3.6.1.4.1.171.10.94.89.89.1.8.0 }
- {name: agent.CpuUtilization5min, oid: .1.3.6.1.4.1.171.10.94.89.89.1.9.0 }

- {name: agent.DramUtilizationTotalDRAM, oid: .1.3.6.1.4.1.171.12.1.1.9.1.2 }
- {name: agent.DramUtilizationUsedDRAM, oid: .1.3.6.1.4.1.171.12.1.1.9.1.3 }
- {name: agent.DramUtilization, oid: .1.3.6.1.4.1.171.12.1.1.9.1.4 }

- {name: agent.SerialNumber, oid: .1.3.6.1.4.1.171.12.1.1.12 }

- {name: agent.PortUtilizationTx, oid: .1.3.6.1.4.1.171.12.1.1.8.1.2 }
- {name: agent.PortUtilizationRx, oid: .1.3.6.1.4.1.171.12.1.1.8.1.3 }
- {name: agent.PortUtilizationUtil, oid: .1.3.6.1.4.1.171.12.1.1.8.1.4 }

