- {name: dlink.PortInfoMediumType, oid: .1.3.6.1.4.1.171.10.76.28.1.1.13.1.2, values: {1: Cooper, 2: Fiber}}
- {name: dlink.sysPortCtrlSpeed, oid: .1.3.6.1.4.1.171.10.76.28.1.1.13.1.3, values: {1: 1G-Full, 2: 100-Full, 3: 100-Half, 4: 10-Full, 5: 10-Half, 6: Auto}}
- {name: dlink.sysPortCtrlOperStatus, oid: .1.3.6.1.4.1.171.10.76.28.1.1.13.1.4, values: {1: Down, 2: 1G-Full, 3: 100-Full, 4: 100-Half, 5: 10-Full, 6: 10-Half, 7: 10G-Full}}
- {name: dlink.sysPortCtrlState, oid: .1.3.6.1.4.1.171.10.76.28.1.1.13.1.11, values: {1: Enabled, 2: Disabled}}
- {name: dlink.sysPortLinkChangeTime, oid: .1.3.6.1.4.1.171.10.76.28.1.1.14.1.5}
- {name: dlink.sysPortCtrlType, oid: .1.3.6.1.4.1.171.10.76.28.1.1.13.1.8, values: {1: FE, 2: GE, 3: SFP-1G, 4: SFP-10G}}


#Port diagnostic
- {name: dlink.CableDiagPortIndex, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.1}
- {name: dlink.CableDiagPortType, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.2, values: {0: FE, 1: GE, 2: Other}}
- {name: dlink.CableDiagLinkStatus, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.3, values: {0: Down, 1: Up, 2: Other}}
#INTEGER  { ok ( 0 ) , open ( 1 ) , short ( 2 ) , open-short ( 3 ) , crosstalk ( 4 ) , mismatch ( 5 ) , linedriver ( 6 ) , unknown ( 7 ) , count ( 8 ) , no-cable ( 9 ) , other ( 10 ) }
- {name: dlink.CableDiagPair3Status, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.4, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair1Status, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.5, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair2Status, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.6, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair4Status, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.7, values: {0: OK, 1: Open, 2: Short, 3: Open-Short, 4: CrossTalk, 5: MisMatch, 6: LineDriver, 7: Unknown, 8: Count, 9: No-Cable, 10: Other}}
- {name: dlink.CableDiagPair3Length, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.8}
- {name: dlink.CableDiagPair1Length, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.9}
- {name: dlink.CableDiagPair2Length, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.10}
- {name: dlink.CableDiagPair4Length, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.11}
- {name: dlink.CableDiagAction, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.12, values: {1: Action, 2: Processing, 3: Other, 4: ActionCarefulMode}}
- {name: dlink.CableDiagStatus, oid: .1.3.6.1.4.1.171.10.76.28.1.35.1.1.13, values: {1: NotRun, 2: Proccessing, 3: LastTestOk, 4: LastTestFailed}}

- name: acl.profile.type
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.2
  values:
    1: L2 (1)
    2: L3v4 (2)
    11: l3v6 (11)
    3: impb (3)
    8: aclQos (8)
    9: userDefined(9)


- {name: acl.profile.rules_count,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.3}
- {name: acl.profile.dst_mac_addr_mask, oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.5}
- {name: acl.profile.src_mac_addr_mask,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.6}
- name: acl.profile.ip_protocol
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.7
  values:
    0: none(0)
    1: icmp(1)
    2: igmp(2)
    6: tcp(6)
    17: udp(17)
    58: icmpv6(58)
    255: ipProtocolMask(255)
- {name: acl.profile.ip_protocol_mask,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.8}

- {name: acl.profile.dst_ip_mask_type,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.9, values: {1: IPv4, 2: IPv6}}
- {name: acl.profile.dst_ip_mask,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.10}
- {name: acl.profile.src_ip_mask_type,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.11, values: {1: IPv4, 2: IPv6}}
- {name: acl.profile.src_ip_mask,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.12}

- {name: acl.profile.dst_port_mask,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.13}
- {name: acl.profile.src_port_mask,  oid: .1.3.6.1.4.1.171.10.76.28.1.15.1.2.1.14}

# В случае с фильтрафией - можно ограничить по типу пакетов и навесить на конкретый порт
- {name: acl.l2rule.ether_type, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.3}
- {name: acl.l2rule.dst_mac_addr, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.4}
- {name: acl.l2rule.src_mac_addr, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.5}
- {name: acl.l2rule.vlan_id, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.6}
- name: acl.l2rule.action
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.11
  values:
    1: allow (1)
    2: drop (2)
    3: mirror (3)
    4: rateLimit(4)
    5: replaceDSCP(5)
    6: replace1P(6)
    7: replaceQueue(7)
    8: replaceVLAN(8)
- {name: acl.l2rule.match_count, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.19}
- {name: acl.l2rule.in_port_list, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.51}
- {name: acl.l2rule.in_vlan_list, oid: .1.3.6.1.4.1.171.10.76.28.1.15.2.1.1.52}

- {name: acl.l3rule.protocol , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.3, values: {1: ICMP, 2: IGMP, 6: TCP, 17: UDP}}
- {name: acl.l3rule.protocol_mask , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.4, values: {}}
- {name: acl.l3rule.dst_ip_addr , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.7, values: {}}
- {name: acl.l3rule.src_ip_addr , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.8, values: {}}
- {name: acl.l3rule.dst_ip_addr_mask , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.9, values: {}}
- {name: acl.l3rule.src_ip_addr_mask , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.10, values: {}}
- {name: acl.l3rule.dst_port , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.11, values: {}}
- {name: acl.l3rule.src_port , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.12, values: {}}
- {name: acl.l3rule.igmp_type , oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.23, values: {}}
- name: acl.l3rule.action
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.25
  values:
    1: allow (1)
    2: drop (2)
    3: mirror (3)
    4: rateLimit(4)
    5: replaceDSCP(5)
    6: replace1P(6)
    7: replaceQueue(7)
    8: replaceVLAN(8)
- name: acl.l3rule.rate_limit # Rate limit for matched packet. В пакетах
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.26
- name: acl.l3rule.port_list # Rate limit for matched packet. В пакетах
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.51
- name: acl.l3rule.vlan_list
  oid: .1.3.6.1.4.1.171.10.76.28.1.15.3.1.1.52
