<?php

namespace SwitcherCore\Modules\DellSwitch;

class System extends \SwitcherCore\Modules\General\Switches\System
{
    use InterfacesTrait;
    function getPrettyFiltered($filter = [])
    {
        $pretty =  parent::getPrettyFiltered($filter); // TODO: Change the autogenerated stub
        
        return $pretty;
    }
}