<?php


namespace SwitcherCore\Modules\CData\FD11XX;


use Exception;
use SnmpWrapper\Oid;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Switcher\Objects\WrappedResponse;

class CtrlOntDescription extends CDataAbstractModule
{
    /**
     * @var WrappedResponse[]
     */
    protected $response = true ;

    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        $iface = $this->parseInterface($filter['interface']);
        if($iface['type'] != 'ONU') {
            throw new \InvalidArgumentException("Allow only for ONU");
        }
        $description = str_replace(' ', '_', $filter['description']);
        $this->checkSnmpRespError($this->snmp->set(
            Oid::init($this->oids->getOidByName('ont.name')->getOid() . ".{$iface['_snmp_id']}")
                ->setType('StringValue')
                ->setValue($description)
        ));
        return $this;
    }

    function getPretty()
    {
        return true; // TODO: Change the autogenerated stub
    }
}

