<?php


namespace SwitcherCore\Switcher\Console;

use Exception;
use Meklis\Network\Console\Helpers\HelperInterface;
use Meklis\Network\Console\SSH;

class SshLazyConnect extends SSH implements ConsoleInterface
{
    protected $host;
    protected $port;
    protected $username;
    protected $password;
    protected $isLogined = false;

    public function exec($command, $add_newline = true, $prompt = null)
    {
        if(!$this->isLogined) {
            $this->isLogined = true;
            $this->connect($this->host, $this->port);
            $this->login($this->username, $this->password);
        }
        return parent::exec($command, $add_newline, $prompt); // TODO: Change the autogenerated stub
    }

    function connectAndLogin() {
        if(!$this->isLogined) {
            $this->connect($this->host, $this->port);
            $this->login($this->username, $this->password);
            $this->isLogined = true;
        }
    }

    function setAccess($username, $password)
    {
       $this->username = $username;
       $this->password = $password;
       return $this;
    }

    function setHost($host, $port = 23)
    {
       $this->host = $host;
       $this->port = $port;
       return $this;
    }
    /**
     * @return \Meklis\Network\Console\Helpers\DefaultHelper|HelperInterface
     */
    function getDeviceHelper()
    {
        return $this->helper;
    }

    function setTimeout($timeout)
    {
        $this->timeout = $timeout;
        return $this;
    }

    function setStreamTimeout($timeout)
    {
        $this->stream_timeout_sec = $timeout;
        return $this;
    }

    function getStream()
    {
        return $this->session;
    }
}
