<?php

namespace SwitcherCore\Modules\EltexSwitch;

class ParseInterface extends \SwitcherCore\Modules\General\Switches\ParseInterface
{
    use InterfacesTrait;
    public function getPrettyFiltered($filter = [])
    {       

        return parent::getPrettyFiltered($filter); // TODO: Change the autogenerated stub
    }
}
