<?php


namespace SwitcherCore\Modules\VsolOlts;


use Exception;
use SwitcherCore\Config\Objects\Oid;
use SwitcherCore\Modules\AbstractModule;
use SwitcherCore\Modules\Helper;
use SwitcherCore\Switcher\Objects\SnmpResponse;
use SwitcherCore\Switcher\Objects\WrappedResponse;

class InterfaceDescriptions extends VsolOltsAbstractModule
{
    /**
     * @var SnmpResponse[]
     */
    protected $response = null;

    function getRaw()
    {
        return $this->response;
    }

    function getPrettyFiltered($filter = [], $fromCache = false)
    {
        return parent::getPrettyFiltered($filter, $fromCache); // TODO: Change the autogenerated stub
    }


    function getPretty()
    {
        $data = [];
        foreach ($this->response as $resp) {
            try {
                $d = [
                    'interface' => $this->parseInterface(".". Helper::getIndexByOid($resp->getOid(), 1) . "." .Helper::getIndexByOid($resp->getOid())),
                    'description' => $resp->getValue() == "NULL" ? '' : $resp->getValue(),
                ];
                if (!$d['interface']['id']) continue;
                $data[] = $d;
            } catch (\Exception $e) {
                $this->logger->error("Error get interface description for interface:" . $e->getMessage());
            }
        }
        return $data;
    }

    /**
     * @param array $filter
     * @return $this|AbstractModule
     * @throws Exception
     */
    public function run($filter = [])
    {
        if ($filter['interface']) {
            $interface = $this->parseInterface($filter['interface']);
            $data = $this->formatResponse(
                $this->snmp->get([
                    \SnmpWrapper\Oid::init($this->oids->getOidByName('ont.description')->getOid() . "{$interface['_snmp_id']}"),
                ])
            );
        } else {
            $data = $this->formatResponse(
                $this->snmp->walk(
                    [
                        \SnmpWrapper\Oid::init($this->oids->getOidByName('ont.description')->getOid()),
                    ]
                )
            );
        }
        $resp = $this->getResponseByName('ont.description', $data);
        if($resp->error()) {
            throw new \Exception($resp->error());
        }
        $this->response = $this->getResponseByName('ont.description', $data)->fetchAll();
        return $this;
    }
}

