<?php


namespace SwitcherCore\Modules\ZTE\C300Series;



use SwitcherCore\Modules\ZTE\ModuleAbstract;

class UniInterfacesControlAdminStatus extends ModuleAbstract
{
    protected $response = null;


    function getPrettyFiltered($filter = [], $fromCache = false)
    {
        return true; // TODO: Change the autogenerated stub
    }


    function getPretty()
    {
        return true;
    }

    /**
     * @param array $filter
     * @return $this|ModuleAbstract
     * @throws \Exception
     */
    public function run($filter = [])
    {
        $iface = $this->parseInterface($filter['interface']);

        if(in_array($this->model->getKey(), [
            'zte_c300_fw_1_2',
            'zte_c320_fw_1_2',
        ])) {
            $this->controlOverConsole($iface, $filter);
        } else {
            $this->controlOverSNMP($iface, $filter);
        }

        $this->response = true;
        return $this;
    }

    public function controlOverConsole($iface, $filter) {
        $this->telnet->exec("conf t");
        $this->telnet->exec("pon-onu-mng {$iface['name']}");
        if($iface['_technology'] === 'epon') {
            throw new \Exception("Method not supported for EPON");
        } else {
            $state = $filter['state'] === 'enable' ? 'unlock':'lock';
            $this->telnet->exec("interface eth eth_0/{$filter['num']} state {$state}");
        }
    }
    public function controlOverSNMP($iface, $filter) {
        if($iface['_technology'] === 'epon') {
            $action = null;
            switch ($filter['state']) {
                case 'enable': $action = 2; break;
                case 'disable': $action = 1; break;
            }
            $oid = \SnmpWrapper\Oid::init($this->oids->getOidByName('epon.uni.admin_state')->getOid() . ".{$iface['_oid_id']}.{$filter['num']}")
                ->setType('Integer')
                ->setValue($action);
        } else {
            $action = null;
            switch ($filter['state']) {
                case 'enable': $action = 1; break;
                case 'disable': $action = 2; break;
            }
            $oid = \SnmpWrapper\Oid::init($this->oids->getOidByName('gpon.uni.admin_state')->getOid() . ".{$iface['_oid_eth_id']}.{$filter['num']}")
                ->setType('Integer')
                ->setValue($action);
        }
        $resp = $this->snmp->set($oid);
        foreach ($resp as $r) {
            if($r->getError()) {
                throw new \SNMPException($r->getError());
            }
        }

    }
}

