- {name: zx.olt.saveConfig, oid: .1.3.6.1.4.1.3902.1082.20.1.2.10.1.1.0, values: {1: save}}

#MAIN BOARD
#- {name: zx.main.temperature, oid: .1.3.6.1.4.1.3902.1015.2.1.3.2}
#- {name: zx.main.VlanName, oid: .1.3.6.1.4.1.3902.1015.20.2.1.2}
#- {name: zx.main.power.voltage, oid: .1.3.6.1.4.1.3902.1015.2.1.3.9.2.1.3} # val / 1000
#- {name: zx.main.power.operState, oid: .1.3.6.1.4.1.3902.1015.2.1.3.9.2.1.2, values: {1: inService, 2: hwOffline, 3: powerFault}}
#- {name: zx.main.power.supplyStatus, oid: .1.3.6.1.4.1.3902.1015.2.1.3.9.2.1.1, values: { 1: normal, 2: overVoltage, 3: underVoltage, 4: off }}

#CARD BLOCK
- {name: zx.slot.RealType, oid: .1.3.6.1.4.1.3902.1082.10.1.2.4.1.4}
- {name: zx.slot.OperStatus, oid: .1.3.6.1.4.1.3902.1082.10.1.2.4.1.5, values: {1: inService, 2: notInService, 3: hwOnline, 4: hwOffline, 5: configuring, 6: configFailed, 7: typeMismatch, 8: deactived, 9: faulty, 10: invalid, 11: noPower}}
#- {name: zx.slot.temperature, oid: .1.3.6.1.4.1.3902.1015.2.1.3.13.5.1.1}
- {name: zx.slot.NumPorts, oid: .1.3.6.1.4.1.3902.1082.10.1.2.4.1.7}
- {name: zx.slot.HardwareVer, oid: .1.3.6.1.4.1.3902.1082.10.1.2.4.1.23}
- {name: zx.slot.FirmwareVer, oid: .1.3.6.1.4.1.3902.1082.10.1.2.4.1.27}

#GENERAL OLT BLOCK
#- {name: zx.olt.OpticalPowerTxCurrValue, oid: .1.3.6.1.4.1.3902.1015.3.1.13.1.4}
#- {name: zx.olt.OpticalSupplyVoltage, oid: .1.3.6.1.4.1.3902.1015.3.1.13.1.10}
#- {name: zx.olt.OpticalVendorName, oid: .1.3.6.1.4.1.3902.1015.3.1.13.1.14}
#- {name: zx.olt.OpticalVendorPn, oid: .1.3.6.1.4.1.3902.1015.3.1.13.1.13}
#- {name: zx.olt.OpticalModuleType, oid: .1.3.6.1.4.1.3902.1015.3.1.13.1.62}

#GPON ONT BLOCK
- {name: gpon.ont.GponName, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.2}
- {name: gpon.ont.GponDescription, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.3}
- {name: gpon.ont.regMode, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.5, values: {12: regModePsk, 11: regModeSnPlusRegisterId, 10: regModeLoidPlusPwd, 9: regModeLoid, 1: regModeSn, 2: regModePwd, 3: regModeSnPlusPwd, 4: regModeRegisterId, 5: regModeRegisterIdPlus8021x, 6: regModeRegisterIdPlusMutual, 7: regModeHexPwd, 8: regModeSnPlusHexPwd}}
- {name: gpon.ont.typeName, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.1}
- {name: gpon.ont.serial, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.6}
- {name: gpon.ont.vportMode, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.11, values: { 1: gemport, 2: onu, 3: manual}}
- {name: gpon.ont.dbaMode, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.3.1.12, values: { 1: gemport, 2: onu, 3: manual}}
- {name: gpon.ont.adminState, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.1, values: { 1: enabled, 2: disabled}}
- {name: gpon.ont.phaseState, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.4, values: { 1: logging, 2: los, 3: syncMib, 4: working, 5: dyinggasp, 6: authFailed, 7: offline}}
- {name: gpon.ont.equipmentId, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.2.1.8}
- {name: gpon.ont.LastOnlineTime, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.5}
- {name: gpon.ont.LastOfflineTime, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.6}
- {name: gpon.ont.LastOfflineReason, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.8.1.7, values: { 1: unknown, 2: los, 3: losi, 4: lofi, 5: sfi, 6: loai, 7: loami, 8: authFail, 9: dyingGasp, 10: deactiveSucc, 11: deactiveFail, 12: reboot, 13: shutdown }}

- {name: gpon.ont.vendorId, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.2.1.1}
- {name: gpon.ont.verFirmware, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.2.1.2}

- {name: gpon.ont.action.reboot, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.10.1.1, values: {1: reboot}}
- {name: gpon.ont.action.restore, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.10.1.3, values: {1: restore}}
- {name: gpon.ont.action.restoreFactory, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.10.1.4, values: {1: restore}}
- {name: gpon.ont.action.restoreWifi, oid: .1.3.6.1.4.1.3902.1082.500.20.2.1.10.1.5, values: {1: restore}}

- {name: gpon.uncfg.serial, oid: .1.3.6.1.4.1.3902.1082.500.10.2.2.5.1.2}
- {name: gpon.uncfg.psw, oid: .1.3.6.1.4.1.3902.1082.500.10.2.2.5.1.3}
- {name: gpon.uncfg.type, oid: ..1.3.6.1.4.1.3902.1082.500.10.2.2.5.1.7}
- {name: gpon.uncfg.fwVersion, oid: .1.3.6.1.4.1.3902.1082.500.10.2.2.5.1.8}
- {name: gpon.uncfg.onlineTime, oid: .1.3.6.1.4.1.3902.1082.500.10.2.2.5.1.9}


- {name: gpon.optical.olt_rx, oid: .1.3.6.1.4.1.3902.1015.1010.11.2.1.2} # $res = val / 1000
- {name: gpon.optical.rx, oid: .1.3.6.1.4.1.3902.1082.500.20.2.2.2.1.10} # $res = $val == 65535 ? null : ($val > 30000) ?  ($val - 65536) * 0.002 - 30 : $val * 0.002 - 30
- {name: gpon.optical.tx, oid: .1.3.6.1.4.1.3902.1082.500.20.2.2.2.1.14} # $res = $val == 65535 ? null : ($val > 30000) ?  ($val - 65536) * 0.002 - 30 : $val * 0.002 - 30
- {name: gpon.optical.temp, oid: .1.3.6.1.4.1.3902.1082.500.20.2.2.2.1.19} # $res = $val / 256
- {name: gpon.optical.voltage, oid: .1.3.6.1.4.1.3902.1082.500.20.2.2.2.1.17} # $res = $val * 0,02
- {name: gpon.optical.distance, oid: .1.3.6.1.4.1.3902.1082.500.10.2.3.10.1.2}

- {name: gpon.uni.admin_state, oid: .1.3.6.1.4.1.3902.1082.500.20.2.3.2.1.5, values: {1: Enabled, 2: Disabled}}
- {name: gpon.uni.admin_speed, oid: .1.3.6.1.4.1.3902.1082.500.20.2.3.2.1.3, values: {1: Auto, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Full, 7: 10G-Full}}
- {name: gpon.uni.status, oid: .1.3.6.1.4.1.3902.1082.500.20.2.3.2.1.6, values: {1: Up, 2: Down}}
- {name: gpon.uni.speed, oid: .1.3.6.1.4.1.3902.1082.500.20.2.3.2.1.7, values: {1: Auto, 2: 10-Half, 3: 10-Full, 4: 100-Half, 5: 100-Full, 6: 1G-Full, 65535: Unknown}}

