<?php

namespace SwitcherCore\Dev;

use SwitcherCore\Switcher\Console\ConsoleInterface;
use SwitcherCore\Switcher\CoreConnector;
use Symfony\Component\Console\Helper\Table;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class SwitcherCoreModules extends AbstractCommand
{
    /**
     * @Inject
     * @var CoreConnector
     */
    protected $swc;
    function configure()
    {
        $this->setName("modules")
            ->setDescription("Allow return modules from device")
            ->addArgument("ip", InputArgument::REQUIRED, "Device ip address")
            ->addOption("community", "c", InputOption::VALUE_OPTIONAL, "Community name", "public")
            ->addOption("username", "u", InputOption::VALUE_OPTIONAL, "Console username", "admin")
            ->addOption("password", "p", InputOption::VALUE_OPTIONAL, "Console password", "admin")
        ;
        parent::configure(); // TODO: Change the autogenerated stub
    }

    function exec(InputInterface $input, OutputInterface $output)
    {

        $ip = $input->getArgument('ip');
        $core = $this->getCore($ip, $input->getOption('community'), $input->getOption('username'), $input->getOption('password'));


        $output->writeln("<comment>Information of device {$input->getArgument('ip')}</comment>");
        $output->writeln("");
        $output->writeln("<comment>Modules: </comment>");
        $table = new Table($output);
        $table->setHeaders([
            'Module name',
            'Called class',
            'Arguments',

        ]);
        foreach ($core->getModulesData() as $module) {
            $arguments = '';
            foreach ($module['arguments'] as $argData) {
                $req = $argData['required'] ? "*" : "";
                $arguments .= "{$argData['name']}$req, pattern: /{$argData['pattern']}/\n";
            }
            $table->addRow([
                $module['name'],
                $module['class'],
                trim($arguments),
            ]);
        }
        $table->render();
    }
}