<?php


namespace SwitcherCore\Switcher\Objects;

use SwitcherCore\Modules\AbstractModule;


/**
 *
 * //For another object names - use Abstract parser
 * @property AbstractModule[] $objects
 * @package SwitcherCore\Switcher\Objects
 */
class ModuleStore extends ObjectStore
{

    /**
     * @var AbstractModule[]
     */
    protected $objects = [];

    /**
     * @param $name
     * @return AbstractModule
     */
    function __get($name)
    {
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
}