<?php


namespace SwitcherCore\Switcher\Objects;


use RouterosAPI;

class RouterOsLazyConnect extends RouterosAPI
{
    protected $ip = "";
    protected $login = "";
    protected $password = "";
    protected $isConnected = false;
    function connect($ip, $login, $password)
    {
        $this->ip = $ip;
        $this->login = $login;
        $this->password = $password;
        return $this;
    }
    function setPort($port) {
        $this->port = $port;
        return $this;
    }
    function setTimeout($timeout_sec) {
        $this->timeout = $timeout_sec;
        return $this;
    }
    function write($command, $param2 = true)
    {
        $this->lazyConn();
        return parent::write($command, $param2); // TODO: Change the autogenerated stub
    }

    function comm($com, $arr = array())
    {
        $this->lazyConn();
        return parent::comm($com, $arr); // TODO: Change the autogenerated stub
    }
    function disconnect()
    {
        if($this->isConnected) {
            parent::disconnect(); // TODO: Change the autogenerated stub
        }
    }
    protected function lazyConn() {
        if(!$this->isConnected) {
            $this->isConnected = true;
            parent::connect($this->ip, $this->login, $this->password);
        }
        return $this;
    }
}