<?php


namespace SwitcherCore\Switcher\Objects;


class TelnetLazyConnect extends \Meklis\TelnetOverProxy\Telnet
{
    protected $is_logined;
    protected $proxy_addr = "";
    protected $timeout = 60;
    protected $username = "";
    protected $password = "";
    protected $host_type = "";

    function connectOverProxy($proxy_addr = "tcp://0.0.0.0:3333", $timeout = 180)
    {
        $this->proxy_addr = $proxy_addr;
        $this->timeout = $timeout;
        return $this;
    }
    function setHostType($host_type) {
        $this->host_type = $host_type;
        return $this;
    }

    function login($username, $password, $host_type="")
    {
        $this->username = $username;
        $this->password = $password;
        return $this;
    }
    function exec($command, $add_newline = true)
    {
        if(!$this->is_logined) {
            parent::connectOverProxy($this->proxy_addr, $this->timeout);
            parent::setLinuxEOL();
            parent::disableMagicControl();
            switch ($this->host_type) {
                case "dlink":
                    parent::login($this->username, $this->password, $this->host_type);
                    parent::exec("disa clip");
                    break;
                default:
                    throw new \Exception("Not supported type of conn_type");
            }
        }
        $this->is_logined = true;
        return parent::exec($command, $add_newline); // TODO: Change the autogenerated stub
    }
    function __destruct()
    {
        try {
            if($this->is_logined) {
                switch ($this->host_type) {
                    case 'dlink':
                        parent::exec("logout");
                        break;
                }
            }
        } catch (\Exception $e) {}
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}
