- {name: rlStack.unitIdTable, oid: .1.3.6.1.4.1.89.107.1} # no oid on MES14XX, MES24XX, MES3708. Added for compatibility on InterfacesTrait

- {name: sfp.ddmValues, oid: .1.3.6.1.4.1.35265.52.1.1.3.2.1.8} # .1.3.6.1.4.1.35265.52.1.1.3.2.1.8.{iface_id}.{type}.1 type - 1: temp (40), 2: vcc (3), 3: tx_bias (21) 4: tx_power (-9393) 5: rx_power (-7304)
- {name: sfp.waveLength, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.4}

- {name: sfp.connectorType, oid: 1.3.6.1.4.1.35265.52.1.1.3.1.1.1, values: {0: unknown, 1: sc, 7: lc, 11: optical-pigtail, 255: vendorspec}}
- {name: sfp.interfaceType, oid: 1.3.6.1.4.1.35265.52.1.1.3.1.1.2, values: {0: unknown, 1: gbic, 2: sff, 3: sfp-sfpplus, 255: vendorspec}}
- {name: sfp.fiberDiameterType, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.7, values: {1: fiber9, 2: fiber50, 3: fiber625, 4: copper, 65535: unknown}}
- {name: sfp.ethComplianceCode, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.3}
- {name: sfp.vendorName, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.5}
- {name: sfp.serialNumber, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.6}
- {name: sfp.transferDistance, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.8} # 10000
- {name: sfp.partNumber, oid: .1.3.6.1.4.1.35265.52.1.1.3.1.1.10}
